### ISSUE TITLE
How to remove "Locale fa not found. Did you forget to load it?"

### ISSUE THREAD

**Issue by eagle-design** [talkhabi/vue-persian-datetime-picker#10]
سلام
همه چیز اوکی هست فقط این وارنینگ میاد

Locale fa not found. Did you forget to load it?

**Comment by talkhabi** [comment]
این مشکل به خاطر مومنت جلالی هست این لینکو ببینید:
https://github.com/jalaali/moment-jalaali/pull/134

**Comment by eagle-design** [comment]
import moment from 'moment-jalaali';
require('moment/locale/fa');
moment.updateLocale('fa');
تاثیری نداشت

**Comment by talkhabi** [comment]
node_modules/moment-jalaali/index.js
این فایل  پیوست شده رو رو جایگزین فایل بالا کنید 

[index.js.zip](https://github.com/talkhabi/vue-persian-datetime-picker/files/1977361/index.js.zip)

**Comment by VahidBo** [comment]
My PR for moment-jalali is merged and released in latest version you can the latest version to avoid facing this warning.

**Comment by VahidBo** [comment]
@talkhabi My PR fot moment-jalali is merged and released in the latest version you can use it to avoid facing this warning.

**Comment by talkhabi** [comment]
@VahidBo Thank you, I will upgrade to the latest version.
