### ISSUE TITLE
مشکل نمایش در تم تاریک

### ISSUE THREAD

**Issue by ali-hallaji** [talkhabi/vue-persian-datetime-picker#100]
<p dir='ltr' align='right'>درود به شما، کارتون عالیه. خواستم یه مشکل مرتبط با پس زمینه عرض کنم که وقتی تم تاریک میشه کل نوشته ها سفید میشه و هیچی معلوم نیست.
من از فریم ورک  Quasarدارم استفاده میکنم و برای همین وقتی روی تم دارک میذارم داشبورد رو کلا هیچی قابل نمایش نیست روی پس زمینه فریم تایم پیکر.
</p>

**Comment by talkhabi** [comment]
سلام، ممنون
این بخاطر رنگ متن هست که به رنگ روشن هست و در پس زمینه سفید مشخص نیست
با css به دیتپیکر رنگ مورد نظر خودتون رو بدید

**Comment by ali-hallaji** [comment]
<p dir="rtl">نمیخوام به استایل خود داشبور دست بزنم.
امکانی هست که دیتپیکر رو متناسب با دیزاین خودمون بکنیم؟
میدونم که هست اما با ذکر مثال خیلی بهتره. بازم یه دنیا ممنون</p>

**Comment by talkhabi** [comment]
نیازی نیست استایل داشبردتون رو دستکاری کنید

```css
.vpd-wrapper {
  color: #333;
}
```
