### ISSUE TITLE
مشکل نمایش تاریخ ماه اول سال

### ISSUE THREAD

**Issue by vfsoraki** [talkhabi/vue-persian-datetime-picker#103]
سلام
ماه اول سال به صورت نادرست نمایش داده میشود.
من روی ios با مرورگرهای فایرفاکس و سافاری تست کردم و این مشکل در هر دو وجود داشت.
یک عکس هم ضمیمه شده که مشکل را نشان می‌دهد.

![image](https://user-images.githubusercontent.com/7745247/79697345-8322f400-8297-11ea-9bf9-c7a4674f238e.png)

**Comment by vfsoraki** [comment]
روی فایرفاکس لینوکس تست کردم مشکلی نداشت.
در صورت امکان روی مرورگرهای دیگر هم تست خواهد میکنم و نتیجه رو اعلام میکنم.

**Comment by talkhabi** [comment]
سلام
این کدوم ورژنش هست؟
ورژن 2.1.5 دیروز پابلیش شد

**Comment by vfsoraki** [comment]
ورژن فعلی ۲.۱.۴ هست
اپدیت میکنم و نتیجه رو هم میگم

**Comment by vfsoraki** [comment]
با اپدیت به ۲.۱.۵ رفع شد.
ممنون
