### ISSUE TITLE
Dark theme compatibility

### ISSUE THREAD

**Issue by AldeonMoriak** [talkhabi/vue-persian-datetime-picker#105]
Hello, how can I change the colors of the datepicker according to my app's theme?
When it is dark days' numbers are not visible.<br/>
![screenshot-b4c958d3](https://user-images.githubusercontent.com/37976890/80233705-2bf09b00-866c-11ea-9a4c-9683e277c8e2.png)

**Comment by alirezat775** [comment]
Hi, i also need dark theme compatibility @talkhabi
