### ISSUE TITLE
problem with safari

### ISSUE THREAD

**Issue by alireza0x0f** [talkhabi/vue-persian-datetime-picker#108]
Hi
it seems it has still problem with safari browser when select datetime.
when i select datetime in safari, it shows correct data but when i read the data it is wrong.

**Comment by talkhabi** [comment]
Hi,
Please explain more, where and how do you read the data?

**Comment by alireza0x0f** [comment]
when i set the date with (picker.date = dateString;) and read it by (date = picker.date) command, it is ok. but when i pick a datetime manually and read it by (date = picker.date), the readed time is 3:30 ( or 4:30 in summer) more than selected time.
the configure is like below:

<div id="time_from" >
        <label>زمان شروع</label>
        <date-picker v-model="date" v-bind:min="dmin" v-bind:max="dmax"
        locale="fa,en" 
        type="datetime" 
        format="YYYY-MM-DDTHH:mm:ss"
        display-format="jYYYY-jMM-jDD HH:mm"
        @change="onChange()"
        :timezone="false">
        </date-picker>  
    </div> 


var picker = new Vue({
        el: '#time_from',
        data: {
            date: '',
            dmin:'',
            dmax:''
        },
        components: {
            DatePicker: VuePersianDatetimePicker
        },
        methods: {
            onChange : function()
            {
                // todo  if safari-> read data and fix it for next reads
                //this.date
            }
        }
    });

-------------------------------------------------------------------
i set timezone to false because picker has a bug with timezone
if timezone is true and i select a time in summer, the time is UTC+4:30
but when i select a time from winter, the time is again UTC+4:30 instead of UTC+3:30

**Comment by alireza0x0f** [comment]
when i set the date with (picker.date = dateString;) and read it by (date = picker.date) command, it is ok. but when i pick a datetime manually and read it by (date = picker.date), the readed time is 3:30 ( or 4:30 in summer) more than selected time.
the configure is like below:

`<div id="time_from" >`
&emsp;`<label>زمان شروع</label>`
&emsp;`<date-picker v-model="date" v-bind:min="dmin" v-bind:max="dmax"`
&emsp;`locale="fa,en" `
&emsp;`type="datetime" `
&emsp;`format="YYYY-MM-DDTHH:mm:ss"`
&emsp;`display-format="jYYYY-jMM-jDD HH:mm"`
&emsp;`@change="onChange()"`
&emsp;`:timezone="false">`
&emsp;`</date-picker>  `
`</div> `


`var picker = new Vue({`
&emsp;        `el: '#time_from',`
&emsp;        `data: {`
&emsp;&emsp;            `date: '',`
&emsp;&emsp;            `dmin:'',`
&emsp;&emsp;            `dmax:''`
&emsp;        `},`
&emsp;       ` components: {`
&emsp;&emsp;           ` DatePicker: VuePersianDatetimePicker`
&emsp;       ` },`
&emsp;        `methods: {`
&emsp;&emsp;           ` onChange : function()`
&emsp;&emsp;           ` {`
&emsp;&emsp;                `// todo  if safari-> read data and fix it for next reads`
&emsp;&emsp;               ` //this.date`
&emsp;&emsp;           ` }`
&emsp;        `}`
   ` });`

-------------------------------------------------------------------
i set timezone to false because picker has a bug with timezone
if timezone is true and i select a time in summer, the time is UTC+4:30
but when i select a time from winter, the time is again UTC+4:30 instead of UTC+3:30

**Comment by talkhabi** [comment]
سلام دوست عزیز
عذرخواهی میکنم بابت اینکه دیر شد
لطفا ورژن جدید رو نصب کنید و مجددا تست کنید
اگر بازهم مشکل داشت بگید
