### ISSUE TITLE
مشکل در انتخاب تاریخ های قدیمی

### ISSUE THREAD

**Issue by marjandejyab** [talkhabi/vue-persian-datetime-picker#11]
سلام روزتون بخیر و خسته نباشید.
امکان انتخاب تاریخ های قبل از بهمن 1349 در این پکیج وجود ندارد.
آیا این موضوع علت خاصی داره؟ و آیا قابل برطرف شدن هست؟
پیشاپیش از پاسخگوییتون سپاسگزارم.

**Comment by marjandejyab** [comment]
بر طرف شد دوست عزیز.
سپاس

**Comment by davodaslanifakor** [comment]
@talkhabi  
so fine ... like  ...
