### ISSUE TITLE
کاراکتر های عدد در سایت تبدیل به کاراکتر های فارسی نمیشوند

### ISSUE THREAD

**Issue by masoudhosseiny** [talkhabi/vue-persian-datetime-picker#110]
کاراکتر های عدد در سایت تبدیل به کاراکتر های فارسی نمیشوند در صورتی که بقیه بخش ها و کلمه ها فارسی هستند

**Comment by talkhabi** [comment]
شما باید از فونتی استفاده کنید که اعداد فارسی داشته باشند
