### ISSUE TITLE
[Vue warn]: Error in render: "Error: Invalid Jalaali year -621"

### ISSUE THREAD

**Issue by Ali12K** [talkhabi/vue-persian-datetime-picker#112]
سلام
مشکل ازچیه؟

**Comment by talkhabi** [comment]
سلام
تاریخ اشتباه به دیتپیکر دادید احتمالا

**Comment by Ali12K** [comment]
سلام ممنون از پاسخگویی 
دقیقا همین طور بود تو برنامه یه مقدار اشتباه را به عنوان تاریخ میدادم. 
بازم ممنون واقعا کارتون حرف نداره....
