### ISSUE TITLE
نمایش تاریخ جاری

### ISSUE THREAD

**Issue by aebrs** [talkhabi/vue-persian-datetime-picker#12]
سلام
راهی هست که تاریخ امروز که در تقویم هست در تکست باکس هم بصورت پیش فرض نمایش داده شود
یا باید از پکیج دیگری استفاد کرد
این پکیج دارای
moment
هست ، آیا راهی دارد که از دستورات آن استفاده کنیم؟
مرسی

**Comment by talkhabi** [comment]
سلام، بله باید از مومنت جلالی استفاده کنید.
این پکیج نیاز به نصب ندارد چون همراه با پلاگین نصب میشود

```HTML
<template>
    <date-picker v-model="date"></date-picker>
</template>

<script>
import moment from 'moment-jalaali';
export default {
    data(){
        return {
            date: moment().format('jYYYY/jMM/jDD'),
        }
    }
}
</script>
````
