### ISSUE TITLE
مشکل فونت فارسی

### ISSUE THREAD

**Issue by ArashKenji73** [talkhabi/vue-persian-datetime-picker#120]
![Screenshot (10)](https://user-images.githubusercontent.com/59219272/90331716-f5001580-dfcb-11ea-83e2-b07d90284f3e.png)
مطابق با راهنما نصب کردم همه چیز درست کار میکنه
فقط فونت های فارسی مورد دارن

**Comment by talkhabi** [comment]
در حال حاضر شما باید از فونت هایی استفاده کنید که اعداد را بصورت فارسی نمایش میدهند
یعنی فونتهایی که اعداد فارسی دارند

**Comment by ArashKenji73** [comment]
> در حال حاضر شما باید از فونت هایی استفاده کنید که اعداد را بصورت فارسی نمایش میدهند
> یعنی فونتهایی که اعداد فارسی دارند

از ایران سانس استفاده میکنم باز هم مشکل دارد

**Comment by ArashKenji73** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/59219272/90334683-af037b80-dfe4-11ea-8347-9ff22a7d62a8.png)

**Comment by ArashKenji73** [comment]
![Screenshot (14)_LI](https://user-images.githubusercontent.com/59219272/90334845-bd05cc00-dfe5-11ea-9ebc-7b43dc49dbc3.jpg)

**Comment by mostafaznv** [comment]
میتونی از اسلات‌ها استفاده کنی و عددی که قراره توی هر آیتم نشون داده بشه رو به کمک فیلترها خودت تبدیل کنی:

```
<template v-slot:day-item="{ vm, day, color }">
    <span class="vpd-day-effect" :style="{ 'background-color': color }" />
    <span class="vpd-day-text">{{ day.formatted | persianNumber }}</span>
</template>
```

**Comment by talkhabi** [comment]
البته تو ورژن 
2.3.0
یه پراپ به نام 
convertNumbers
اضافه شده که اعداد رو به فارسی تبدیل میکنه

https://github.com/talkhabi/vue-persian-datetime-picker/blob/c90ecd3a85d54b29af28ef1bc1bdec32d328aafc/src/picker/VuePersianDatetimePicker.vue#L790
