### ISSUE TITLE
value and initialValue props not working properly

### ISSUE THREAD

**Issue by DivineAlien** [talkhabi/vue-persian-datetime-picker#122]
وقتی یه فرم رو واسه  ادیت کردن با مقدار اولیه رندر میکنم اون مقدار اولیه رو به صورت کاراکتری داخل اینپوت نشون نمیده

I have this component:
```
<date-picker v-model="date" name="deadline" type="datetime" value="1396/05/05 22:50" initial-value="1396/05/05 22:50"></date-picker>
```
and registered it with npm:
```
import VuePersianDatetimePicker from 'vue-persian-datetime-picker';
Vue.component('date-picker', VuePersianDatetimePicker);


const app = new Vue({
    el: '#app',
    data() {
        return {
            date: '',
        }
    }
});
```
I want to have an initial value for edit pages but it's mysteriously not working no console errors or warnings I don't know what to do...

the `name` and `type` works fine.

edit:
- vue version : 2.6.12

also when I watch the app with Vue dev tools I get this(after loading the page):
```
initialValue: "1396/05/05 22:50"
value: ""
```
and actually initialValue works if I click on the calendar icon I can see the default values are already chosen. but it doesn't show the date numbers on input on loading the page.

is there a way to show initialValue date in text format on input?

**Comment by talkhabi** [comment]
Hi @DivineAlien 
You can not use the `v-model` and `value` together
Try this example:
```html
<date-picker v-model="date" name="deadline" type="datetime" initial-value="1396/05/05 22:50"></date-picker>
<script>
const app = new Vue({
    el: '#app',
    data() {
        return {
            date: ''
           // or 
           // date: '1396/05/05 22:50'
        }
    }
});
</script>
```

**Comment by DivineAlien** [comment]
Hello Mr @talkhabi 
in my project there are two ways for me to pass information to this view component:
- making an api
- vue props

so your suggestion doesn't work.

I suggest this instead:
[https://github.com/talkhabi/vue-persian-datetime-picker/blob/94fb6d50a9d3771cc6b265f50ca44559d1ed5ed0/src/picker/VuePersianDatetimePicker.vue#L797](change this line)

to this:
```
date: this.initialValue || null
```

**Comment by talkhabi** [comment]
Are you serious 😐?

There is a prop named `value` to pass the current value of picker,
If you want to specify the current value of picker, you can use `value`.
But if you do not have the value at start, you can specify `initial-value` to force picker to display a date.
