### ISSUE TITLE
Problem with datetime disable

### ISSUE THREAD

**Issue by MOstadi** [talkhabi/vue-persian-datetime-picker#123]
سلام و تشکر از پکیجتون. 

تو  نوع 
datetime 
 بجای اینکه فقط ساعت 12 غیرفعال بشه، کل روز غیر فعال میشه
مثال های توی راهنمای پکیجتونم چک کردم همین مشکلو داشتن:

Regular Expressions
`<date-picker type="datetime" :disable="/1397\/05\/0[1-9] 12:(.*)/" />`

Array of strings and RegExp
`<date-picker type="datetime" :disable="['1397/05/06 12:00', /(.*)22:(.*)/]" />`

**Comment by talkhabi** [comment]
سلام دوست عزیز
عذر خواهی میکنم بابت اینکه دیر شد
این مشکل برطرف شد لطفا ورژن جدید رو نصب کنید اگر بازهم مشکل داشت مطرح کنید
