### ISSUE TITLE
مشکل در پاک کردن مقدار فیلد

### ISSUE THREAD

**Issue by amirzpr** [talkhabi/vue-persian-datetime-picker#125]
سلام.
من در مورد پاک کردن مقداری که به یه فیلد وارد میشه، به مشکل برخوردم. یعنی با کلیک روی دکمه ضربدر کنار فیلد مقداری که از قبل وارد شده، پاک نمیشه.

```javascript
import VuePersianDatetimePicker from 'vue-persian-datetime-picker';
Vue.use(VuePersianDatetimePicker, {
    name: 'date-picker',
    props: {
        clearable: true,
        altFormat: 'YYYY-MM-DD HH:mm:ss',
    },
});
```

```html
  <date-picker type="datetime" alt-name="started_at"></date-picker>
```

![image](https://user-images.githubusercontent.com/45946337/92108964-70036180-edfd-11ea-9235-bf1d2ad27a0a.png)

مشکل از کجاست؟

**Comment by talkhabi** [comment]
سلام 
شما v-model ست نکردید
احتمالا بخاطر همینه

**Comment by amirzpr** [comment]
اگه
 v-model 
ست کنم، لازم میشه که تو 
instance
اصلی اپ، مقدارش رو 
initialize
کنم. وگرنه ارور میده. به خاطر همین ست نکردم.
اینجوری اینستنس اصلی اپ پر میشه از همین مقادیر که تو صفحات مختلف با اسم های مختلف ازشون استفاده شده.

راهی جز این وجود نداره؟

**Comment by talkhabi** [comment]
سلام عذر میخوام بابت دیر پاسخ دادن
این مشکلتون حل شد یا خیر؟
از z-index نیست؟

**Comment by amirzpr** [comment]
سلام. خواهش میکنم 💙

مشکل که از همون ست نکردن
v-model
هستش.
ترجیح دادم با ست کردنش یا استفاده تو کامپوننت مشکلشو برطرف کنم.

فکر کنم اگه چاره ای برای عمل کردن دکمه پاک کردن مقدار در حالتی که 
v-model
ست نشده پیدا بکنید، خیلی خوب میشه.

به هر حال یه دنیا ممنون از اینکه این کتابخونه فوق العاده رو به صورت رایگان در اختیار ما قرار دادین ❤

**Comment by talkhabi** [comment]
سلام مجدد
خواهش میکنم وظیفست
این مشکل برطرف شده، لطفا ورژن جدید رو نصب کنید
