### ISSUE TITLE
support for vue 3

### ISSUE THREAD

**Issue by RezaErfani67** [talkhabi/vue-persian-datetime-picker#127]
please modify it for using at vue-next(version 3 of vuejs)
thank you

**Comment by ghonchesefidi** [comment]
Same request. Thanks for review

**Comment by Seven7up** [comment]
> 
> 
> Same request. Thanks for review

When will it be ready for version 3?

**Comment by alireza-orouji** [comment]
منم خیلی نیاز دارم به این کامپوننت توی ویو 3

**Comment by alireza-orouji** [comment]
همه پروژه رو با ویو 3 بالا آوردم بعد دیدم کامپوننت شما ویو 3 رو ساپورت نمیکنه
لطفا میشه اعلام کنین کی این کامپوننت رو آپدیت میکنین؟

**Comment by alireza-orouji** [comment]
لطفا اگر نسخه جدید خیلی دیر حاضر میشه 
میتونین راهی برای استفاده از نسخه فعلی در ویو 3 پیشنهاد بدین
اصلا نمیدونم راهی هست؟

**Comment by Seven7up** [comment]
> 
> 
> لطفا اگر نسخه جدید خیلی دیر حاضر میشه
> میتونین راهی برای استفاده از نسخه فعلی در ویو 3 پیشنهاد بدین
> اصلا نمیدونم راهی هست؟

فعلا از این میتونید استفاده کنید

https://github.com/irdeveloper89/vuejs3-jalali-calendar

**Comment by saeed-darestany** [comment]
vue 3

**Comment by Mahan-Shoghy** [comment]
vue 3

**Comment by keleshteri** [comment]
VUE 3, please... Thanks

**Comment by amirh715** [comment]
`Uncaught (in promise) TypeError: Cannot read property 'allowRecurse' of null`
Is it related to Vue 3?

**Comment by talkhabi** [comment]
Here is a version for vue3
Thanks to pursuelu 
https://github.com/pursuelu/vue3-persian-datetime-picker

**Comment by talkhabi** [comment]
Support for Vue3 will be publish soon.
Thanks for the patience.
