### ISSUE TITLE
datetime بایند کردن فیلدهایی از نوع 

### ISSUE THREAD

**Issue by naderi4** [talkhabi/vue-persian-datetime-picker#128]
سلام و خسته نباشید
موقعه بایند کردن مقادیر تاریخ به صورت متنی مشکلی نیست
 خطا میده  datetime ولی موقعه بایند کردن مقادیر 

`<date-picker v-model="item.birthDate" display-format="jYYYY/jMM/jDD" />`

لایبرری
typeorem
بانک اطلاعاتی 
sqlite
مشخصات فیلد 
 birthDate?: Date;

خطا:
[Vue warn]: Invalid prop: type check failed for prop "value". Expected Number, String, got Date 
found in
---> <DatePicker>

**Comment by talkhabi** [comment]
سلام این مشکل رفع شد
به اینصورت استفاده کنید:
```html
<date-picker v-model="item.birthDate" display-format="jYYYY/jMM/jDD" format="date" />
```
