### ISSUE TITLE
استفاده از تایم استمپ برای ورودی

### ISSUE THREAD

**Issue by m-alinasab** [talkhabi/vue-persian-datetime-picker#13]
با سلام و احترام خدمت شما جناب تلخابی ، وقت بخیر .

ممنون بابت پکیج خیلی خوب و زیبایی که زحمت طراحیش رو کشیدید .

سوال : 
آیا امکانش هست که مقدار ورودی رو بصورت تایمستمپ یا یونیکس دیت وارد کرد که سیستم تبدیل کنه ؟

سوال دوم : 
آیا پکیج شما قابلیت پشتیبانی از تاریخ میلادی رو داره ؟
سیستمی نوشتم که بصورت دو زبانه هست ( فارسی و انگلیسی ) و میخوام پکیج شمارو طوری استفاده کنم که اگر زبان سیستم فارسی بود ،‌ دیت پیکر شمسی و اگر انگلیسی بود ، دیت پیکر میلادی رو بارگذاری کنم

چنین امکانی وجود داره ؟

ممنون میشم راهنماییم کنید .
متشکرم .

**Comment by talkhabi** [comment]
سلام روز بخیر، مچکر 
 مورد اول بله امکانش هست بصورت زیر
```html 
<template>
  <date-picker v-model="date" format="x" display-format="jYYYY/jMM/jDD"></date-picker>
</template>

<script>
    export default {
        data() {
            return {
                date: 1528186032571
            }
        }
    }
</script>
```
اما سوال دوم خیر امکانش فعلا نیست.
موفق باشید.

**Comment by m-alinasab** [comment]
ممنون از شما و توضیحتون .

اگر میشد فوق العاده بود
پکیج آقای باباخانی این قابلیت رو داره که اگر میشد تبدیلش  کرد به پکیج vue  عالی میشد

آپشن های کانفیگش خیلی خوبه و گزینه های جالبی گذاشته براش

http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/

امکانش هست گزینه تاریخ میلادی رو به پکیجتون اضافه کنید ؟

**Comment by talkhabi** [comment]
حتما بررسی میکنم اگر امکانش بود اضافه میکنم
