### ISSUE TITLE
unix timestamp problem

### ISSUE THREAD

**Issue by amidmm** [talkhabi/vue-persian-datetime-picker#132]
I want the output as unix timestamp and I'm using the following script:
```
<date-picker
            format="unix"
            display-format="jYYYY/jMM/jDD"
            placeholder="زمان انقضاء"
            :editable="true"
            locale="fa,en"
            v-model="form.tokenMinExpiry"
            type="date"
            class="datepicker"
            clearable
            :disabled="disabledIfAdmin"
          />
```
The problem is with the input textbox. It always shows today no matter which day I'd chosen from the datepicker. The binded variable, "form.tokenMinExpiry", shows the correct timestamp!

**Comment by talkhabi** [comment]
Use `format="x"` instead of `format="unix"`
