### ISSUE TITLE
ios bug

### ISSUE THREAD

**Issue by PouryaNoufallah96** [talkhabi/vue-persian-datetime-picker#134]
با سلام
وقتی توی دستگاه با ایفون تاریخ انتخاب میکنم تاریخ "null"میشه 
ولی توی بقیه دستگاه ها اکی هست

**Comment by talkhabi** [comment]
سلام و درود،
کروم یا سافاری؟ کدوم نسخش؟

**Comment by PouryaNoufallah96** [comment]
Salam🙏🏻Rooye chrome oke . Too safari che to iphone che tooye mac hardo null mishe

**Comment by talkhabi** [comment]
سلام مجدد
من روی سافاری هم تست کردم مشکلی ندیدم
اگه میشه یه نمونه ایجاد کنید مثلا در سایت
jsfiddle
تا چک کنم ببینم چه حالتی پیش اومده
