### ISSUE TITLE
cannot autofocus on datePicker...

### ISSUE THREAD

**Issue by DevIsShortForDevil** [talkhabi/vue-persian-datetime-picker#136]
Hi , I'm using the datepicker and it's editable and I want to autofocus on the input field ! so far even using ref with focus() didn't work for me ! is there a way to do this ?

**Comment by talkhabi** [comment]
Hi @DevIsShortForDevil you can use native javascript methods for focus, like this example:

`this.$refs.datepicker.$el.querySelector('input').focus()`

I'll fix this problem soon.
