### ISSUE TITLE
Does this library support 12-hour format on selecting time?

### ISSUE THREAD

**Issue by nakarimi** [talkhabi/vue-persian-datetime-picker#140]
I searched in the setting and configuration, but can't find any setting about 12-hour format or AM-PM.

So is this package support this format, if so is there any alternative way to achieve this format on the time selection popup as well on the input display format?

**Comment by talkhabi** [comment]
No, but you can use `min` and `max` for time
`<picker type="time" min="00:00" max="12:00" />`
(the AM-PM not supported in this example)
