### ISSUE TITLE
خارجی بودن اعداد تقویم 

### ISSUE THREAD

**Issue by arhariri79** [talkhabi/vue-persian-datetime-picker#143]
سلام 
با تشکر از پکیج خوبتون 
من پکیج رو با یارن اضافه کردم منتها اعدادم همه خاجی هستند نه فارسی لطفا راهنمایی کنید.

**Comment by talkhabi** [comment]
سلام 
راه اول اینه  که از فونت با اعداد فارسی استفاده کنید
راه دوم هم بصورت زیر:


```html
<date-picker convert-numbers />
```

**Comment by arhariri79** [comment]
خیلی ممنون بابت راهنماییتان
