### ISSUE TITLE
حذف کردن باتن اکنون

### ISSUE THREAD

**Issue by arhariri79** [talkhabi/vue-persian-datetime-picker#144]
من می خواستم دکمه اکنون را از  دیالوگ حذف کنم ولی همچین امکانی وجود ندارد

**Comment by talkhabi** [comment]
به این صورت امکان پذیره:

```html
<date-picker :show-now-btn="false" />
```

**Comment by arhariri79** [comment]
خیلی ممنون با یه بدبختی خودم کدش رو زدم با document ممنون از لطفتون

**Comment by arhariri79** [comment]
انصافا پکیجتون خیلی خوبه ممنون واقعا
