### ISSUE TITLE
نمایش دو ماه با هم 

### ISSUE THREAD

**Issue by javadrohani** [talkhabi/vue-persian-datetime-picker#146]
سلام خسته نباشید آقای تلخابی
میخواستم ببینم آیا امکانی وجود داره که دوماه از تاریخ رو با هم نمایش بدیم  . ؟
ممنون

**Comment by AliRezaBeitari** [comment]
Any updates?

**Comment by talkhabi** [comment]
سلام زنده باشید
خیر امکانش نیست فعلا
منظورتون چطوری هستش؟ مثلا ماه فعلی و قبلش یا بعدش؟
یا دوماه متفاوت از سالهای متفاوت؟
اگر پلاگین خاصی هم مدنظرتونه که این مورد رو داره لطفا ذکر کنید تا بررسی کنم

**Comment by AliRezaBeitari** [comment]
بله دو ماه پشت سر هم رو بتوان مثل سایت علی بابا نمایش داد.

![Screen Shot 2021-08-04 at 12 10 24 AM](https://user-images.githubusercontent.com/21037809/128076136-34710dc6-3d14-44d0-8f16-61f53cc8d962.png)

**Comment by talkhabi** [comment]
سلام مجدد
خیر متاسفانه چننین قابلیتی نداره این پلاگین
