### ISSUE TITLE
Dari Months/ ماه های باستانی

### ISSUE THREAD

**Issue by nakarimi** [talkhabi/vue-persian-datetime-picker#148]
I want to use the name of Afghanistan months like حمل-سنبله, how it is possible, I search the whole project but can't find the Iranian names to replace with afghans, would you give me the solution?, if there is any feature that I didn't found please share with me.

![image](https://user-images.githubusercontent.com/28529970/110205010-cb3d0c00-7e93-11eb-855c-7e4bbc1d7dc1.png)

**Comment by talkhabi** [comment]
https://github.com/talkhabi/vue-persian-datetime-picker/issues/27
