### ISSUE TITLE
وقتی از Custom Input استفاده میشه display-format کار نمیکنه

### ISSUE THREAD

**Issue by keyvanmatinrad** [talkhabi/vue-persian-datetime-picker#149]

**Comment by alireza2281** [comment]
با این روش میشه
`<date-picker ref="datePicker" type="date" vmodel="selectedDate" element="fromtime" format="YYYY-MM-DD" display-format="jYYYY/jMM/jDD" @change="selectDate"/>`
`<input v-model="displaySelectedDate" id="from-time" >`

`data() {
    return {
      displaySelectedDate: '',
      selectedDate: ''
    }
  }`

`methods: {
    selectDate() {
      this.displaySelectedDate = this.$refs.datePicker.displayValue      
    },  
  }`

**Comment by keyvanmatinrad** [comment]
سلام آقا علیرضا
دم شما گرم کار کرد و کارمو قشنگ راه انداخت. امیدوارم همیشه موفق و پیروز باشید. ممنونم از شما

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by niloofarfs** [comment]
<div dir="rtl">


سلام

من هم با display-format مشکل دارم.

در اصل می‌خوام تو یه کد آماده، به جای flatpickr از تاریخ شمسی استفاده کنم:
کدی که نمی‌تونم تغییرش بدم اینه:
</div>


```
<input is="flat-pickr" class="form-control item-datestart select" type="datetime-local" tabindex="1"
	name="<?= $enc->attr( $this->formparam( array( 'item', 'product.datestart' ) ) ) ?>"
	placeholder="<?= $enc->attr( $this->translate( 'admin', 'YYYY-MM-DD hh:mm:ss (optional)' ) ) ?>"
	v-bind:value="`<?= $enc->js( $this->datetime( $this->get( 'itemData/product.datestart' ) ) ) ?>`"
	v-bind:disabled="`<?= $enc->js( $this->site()->readonly( $this->get( 'itemData/product.siteid' ) ) ) ?>` !== ''"
	v-bind:config="Aimeos.flatpickr.datetime" />
‍‍

```


<div dir="rtl">

و کد جاوااسکریپتی که نوشتم برای جایگزین کردن:
</div>

‍‍‍
```
Vue.use(VuePersianDatetimePicker,  {
	name: 'flat-pickr',
	props: {
		inputFormat: "YYYY-MM-DD",
		format: "YYYY/MM/DD",
		clearable: true,
		editable: false,
		color: 'var(--bs-primary, #30a0e0)',
		autoSubmit: false,
	}
});
```



<div dir="rtl">

با این تنظیمات تاریخی که انتخاب می‌کنم شمسیه، و همون تاریخ رو به میلادی در اینپوت نشون می‌ده و به درستی هم میلادی سابمیت می‌شه.


ولی اگه displayFormat استفاده کنم تا تاریخ اینپوت به شمسی نمایش داده بشه، 
همون فرمت شمسی نمایش داده شده رو سابمیت می‌کنه.

چه طوری می‌تونم بدون تغییر تگ input درستش کنم؟

</div>

**Comment by alireza2281** [comment]
<div dir="rtl">
@niloofarfs 

سلام

این input که الان داریو فقط واسه نمایش تاریخ ازش استفاده کن و v-model اصلی که قرار هست تاریخ میلادی رو نگه داره رو به خود کامپوننت `VuePersianDatetimePicker` بده و بعد روی `@change`  کامپوننت بیا مقداره input رو بروزرسانی کم

</div>
