### ISSUE TITLE
Problem with type year

### ISSUE THREAD

**Issue by btechn01** [talkhabi/vue-persian-datetime-picker#150]
Hi, 
Go to the demo page [(DEMO)](https://talkhabi.github.io/vue-persian-datetime-picker/)
In year section  `<date-picker v-model="year" type="year" />` select a year except current year 
The selected year is the current year!
This issue also happens in yearMonth, month
Thank you for the package

**Comment by Aminfrp** [comment]
راس میگه بنده خدا منم همچین باگی دارم وقتی عوض میکنیم سال رو اون بالا عوض نمیشه
