### ISSUE TITLE
آیا انتخاب زمان می تواند شامل ثانیه هم شود؟

### ISSUE THREAD

**Issue by masoodmrx** [talkhabi/vue-persian-datetime-picker#151]
### **آیا انتخاب زمان می تواند شامل ثانیه هم شود؟**
![image](https://user-images.githubusercontent.com/29932641/111906694-0e3bd980-8a67-11eb-9741-d478510ba761.png)
![image](https://user-images.githubusercontent.com/29932641/111906669-e51b4900-8a66-11eb-9998-498299b08cb7.png)

**Comment by talkhabi** [comment]
سلام
خیر متاسفانه این ویژگی پشتیبانی نمیشود
