### ISSUE TITLE
درخواست ثبت توضیحات در تقویم

### ISSUE THREAD

**Issue by Misaghahmadi97** [talkhabi/vue-persian-datetime-picker#153]
سلام
وقتتون به خیر
 میخواستم امکان اضافه کردن توضیحات به روزهای هفته و تاریخ های خاصی رو قرار بدید و این امکان توی تقویم انتخاب روز هم قابل نمایش باشه.
برای مثال برای روز های شنبه بشه ساعت کاری نوشت . برای یه تاریخ خاص بشه ساعت کاری متفاوت نوشت
ممنون از لطفتون

**Comment by talkhabi** [comment]
سلام دوست عزیز
این مواردی که فرمودید برای تقویم هست نه دیتپیکر
باید پلاگین مجزایی برای تقویم نوشته بشه
