### ISSUE TITLE
اشتباه در تاریخ اکنون

### ISSUE THREAD

**Issue by profmamad** [talkhabi/vue-persian-datetime-picker#157]
تاریخ اکنون رو اشتباه متوجه میشه! تاریخ کامپیوتر کلاینت هم کاملا فیکسه! میشه دستی بهش اکنون رو داد؟

روی تاریخ 0778/12/13 هست اکنونش

**Comment by talkhabi** [comment]
تاریخ اکنون درواقع تاریخی هست که پلاگین مومنت با توجه به تاریخ سیستم برمیگردونه
باید دقیق تر بررسی بشه
یا حداقل اینکه نمونه قابل تست و بررسی باشه تا بتونم چک کنم
