### ISSUE TITLE
Uncaught TypeError: (event.target.className || "").indexOf is not a function

### ISSUE THREAD

**Issue by ebrahimimasod** [talkhabi/vue-persian-datetime-picker#161]
سلام
 ممنون به خاطر این پکیج عالی 👍 
 : من  با این پرامتر ها استفاده می کنم  

- altFormat:""
altName:""
appendTo:null
autoSubmit:false
clearable:false
color:"var(--primary)"
compactTime:false
convertNumbers:false
disable:undefined
disabled:false
displayFormat:""
editable:false
element:"my-custom-editable-input"
format:"HH:mm"
highlight:null
initialValue:""
inline:false
inputClass:"form-control"
inputFormat:""
jumpMinute:1
label:""
locale:"en"
localeConfig:Object (empty)
max:null
min:null
multiple:false
name:undefined
placeholder:""
popover:false
range:false
roundMinute:false
show:false
showNowBtn:true
timezone:false
type:"time"
value:"8:00"
view:"day"
wrapperSubmit:false

 : وقتی که دقیقه یا ساعت رو عوض میکنم  به درستی کار می کنند اما توی کنسول این خطا رو میده 

`
VM5412:62 Uncaught TypeError: (event.target.className || "").indexOf is not a function
    at onDoubleClick (eval at success (kernel.js:1), <anonymous>:62:48)
    at dispatch (jquery.js:5237)
    at elemData.handle (jquery.js:5044)
`

**Comment by talkhabi** [comment]
سلام ممنون از شما
من دقیقا همین مورد رو تست کردم و هیچ خطایی در کنسول ندیدم
اگر مقدور بود نمونش رو در 
jsfiddle 
یا جای دیگه بزارید تست میکنم
ممنونم
