### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'allowRecurse' of null

### ISSUE THREAD

**Issue by amirh715** [talkhabi/vue-persian-datetime-picker#163]
Hello. I'm using Vue 3 with this library but I get the following error:
`Uncaught (in promise) TypeError: Cannot read property 'allowRecurse' of null`

**Comment by talkhabi** [comment]
Hi @amirh715 this repo is for vue2
for Vue3 refer to this repo
https://github.com/pursuelu/vue3-persian-datetime-picker
