### ISSUE TITLE
jumpMinute in datatime type

### ISSUE THREAD

**Issue by kevin700523** [talkhabi/vue-persian-datetime-picker#165]
Hi
Thanks for your great work!
I would like to know how to use jumpMinute in datatime mode.
Thank you!

**Comment by talkhabi** [comment]
Hi @kevin700523, thanks.
Have you tried this?
```html
<date-picker
  v-model="datetime"
  type="datetime"
  :jump-minute="15"
  :round-minute="true"
/>
```

**Comment by kevin700523** [comment]
yes i tried this. but it doesn't work.

**Comment by talkhabi** [comment]
I tested this, no problem
What version are you using?
