### ISSUE TITLE
استفاده در لاراول

### ISSUE THREAD

**Issue by Mohammad99k** [talkhabi/vue-persian-datetime-picker#166]
سلام وقتتون بخیر
ممنون میشم در مورد استفاده از پکیج در لاراول راهنمایی بفرمایید

**Comment by talkhabi** [comment]
سلام و روز بخیر
تفاوتی با بقیه کامپوننت ها ندارد
در فایل 
resources/js/app.js
ایمپورت و رجیستر کنید

```javascript
import VuePersianDatetimePicker from 'vue-persian-datetime-picker';
Vue.component('date-picker', VuePersianDatetimePicker);
```

**Comment by talkhabi** [comment]
داکیومنت لاراول برای این بخش:
https://laravel.com/docs/7.x/frontend

**Comment by Mohammad99k** [comment]
سپاس
