### ISSUE TITLE
صفحه سفید و خطای ReferenceError: "date is not defined"

### ISSUE THREAD

**Issue by AGhasemzadeh** [talkhabi/vue-persian-datetime-picker#17]
سلام
وقت بخیر
با تشکر از پکیج بسیار عالی که درست کردید
من وقتی می خواهم از این بسته استفاده کنم
مثل زیر عمل می کنم
import VuePersianDatetimePicker from 'vue-persian-datetime-picker';
Vue.component('date-picker', VuePersianDatetimePicker);

ولی یک صفحه سفید دریافت می کنم
و خطای
ReferenceError: "date is not defined"
را دریافت می گکنم.

میشه بدونم مشکل کجاست.

**Comment by talkhabi** [comment]
سلام ممنون روزبخیر
مشکل اینجاست که 
`date`
رو احتمالا در دیتا تعریف نکردید
` <date-picker v-model="date"></date-picker>`
بجاش اینو امتحان کنید
` <date-picker></date-picker>`

**Comment by talkhabi** [comment]
بله جواب میدهد
داکیومنت را مطالعه بفرمایید

**Comment by AGhasemzadeh** [comment]
بله شد
ولی پس از انتخاب تاریخ در
input
نمایش نمی دهد.
                                            <input
                                                    name="birth_at"
                                                    type="text"
                                                    class="form-control{{ $errors->has('birth_at') ? ' is-invalid' : '' }}"
                                                    id="birth_at"
                                                    placeholder="تاریخ تولد">
                                            <date-picker
                                                    format="jYYYY/jMM/jDD"
                                                    element="birth_at">
                                            </date-picker>
