### ISSUE TITLE
Uncaught TypeError: Cannot read property '_c' of undefined

### ISSUE THREAD

**Issue by ninja71-mn** [talkhabi/vue-persian-datetime-picker#171]
سلام من توی استفاده از پکیجتون با لاراول8 و ویو3 به مشکل خوردم
موقع نمایش صفحه یسری وارنینگ و یه خطا میده، ممنون میشم راهنمایی کنید

admin.js
__
import Select2 from 'vue3-select2-component';
import Pagination from 'v-pagination-3';
import VuePersianDatetimePicker from 'vue-persian-datetime-picker';

app.component('date-picker', VuePersianDatetimePicker);
_____________________________________________________________
create.vue
__
<date-picker v-model="newPerson.birth_date" format="x" display-format="jYYYY/jMM/jDD"></date-picker>
___________________________________________________________
consoleError
___
[Vue warn]: `beforeDestroy` has been renamed to `beforeUnmount`. 
  at <DatePicker modelValue="" onUpdate:modelValue=fn format="x"  ... > 
  at PersonsCreate
  at App

runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Property "$createElement" was accessed during render but is not defined on instance. 
  at <DatePicker modelValue="" onUpdate:modelValue=fn format="x"  ... > 
  at PersonsCreate
  at App

[Vue warn]: Property "_self" was accessed during render but is not defined on instance. 
  at <DatePicker modelValue="" onUpdate:modelValue=fn format="x"  ... > 
  at PersonsCreate
  at App

runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Unhandled error during execution of render function 
  at <DatePicker modelValue="" onUpdate:modelValue=fn format="x"  ... > 
  at PersonsCreate
  at App

Uncaught TypeError: Cannot read property '_c' of undefined
    at Proxy.n (vue-persian-datetime-picker.js?55eb:3)
    at renderComponentRoot (runtime-core.esm-bundler.js?5c40:732)
    at componentEffect (runtime-core.esm-bundler.js?5c40:4225)
    at reactiveEffect (reactivity.esm-bundler.js?a1e9:42)
    at effect (reactivity.esm-bundler.js?a1e9:17)
    at setupRenderEffect (runtime-core.esm-bundler.js?5c40:4208)
    at mountComponent (runtime-core.esm-bundler.js?5c40:4167)
    at processComponent (runtime-core.esm-bundler.js?5c40:4127)
    at patch (runtime-core.esm-bundler.js?5c40:3745)
    at mountChildren (runtime-core.esm-bundler.js?5c40:3927)

**Comment by talkhabi** [comment]
سلام لطفا ورژن سازگار با ویو سه رو نصب کنید
https://github.com/talkhabi/vue3-persian-datetime-picker
https://www.npmjs.com/package/vue3-persian-datetime-picker
