### ISSUE TITLE
Range Select: default selected day issue on month changing

### ISSUE THREAD

**Issue by alisdg** [talkhabi/vue-persian-datetime-picker#172]
in range select , a day will select automatically after trying to change month with label-containing button.
I have attached some screenshots to explain the issue easier. [ in picture#3 a day(13 فروردین ) is already selected]

Thanks.
![1](https://user-images.githubusercontent.com/46891299/132092093-a0f7386f-e6c8-4c50-ac14-e027273a6937.JPG)
![2](https://user-images.githubusercontent.com/46891299/132092094-984ad77c-a1ec-4986-a896-47320413d731.JPG)
![3](https://user-images.githubusercontent.com/46891299/132092095-3a0b92e0-c55b-44ef-ba9e-e8c02dd8f8fe.JPG)

**Comment by alisdg** [comment]
in range select , a day will select automatically after trying to change month with label-containing button.
I have attached some screenshots to explain the issue easier. [ in picture#3 a day(13 فروردین ) is already selected]

Thanks.
![1](https://user-images.githubusercontent.com/46891299/132092031-01f166c7-6b6d-44d8-be73-9188188adbfa.JPG)
![2](https://user-images.githubusercontent.com/46891299/132092032-801cd9b0-cac4-4005-b593-e2cb955af370.JPG)
![3](https://user-images.githubusercontent.com/46891299/132092034-f44d8163-af6b-4fbf-8e9b-ff3c249fe0a7.JPG)

**Comment by talkhabi** [comment]
Oops this problem is due to the effect of [this PR](https://github.com/talkhabi/vue-persian-datetime-picker/pull/152).
I'll fix it
