### ISSUE TITLE
Get the first and last day of each year

### ISSUE THREAD

**Issue by Niaz-estefaie** [talkhabi/vue-persian-datetime-picker#173]
First of all thanks for your great work.
I need to get the first and last day of each year dynamically and bind it with date picker.
I want to know how to do it because as you know some years are 366 days and I have no idea how to handle it dynamically.

**Comment by talkhabi** [comment]
Thank you @Niaz-estefaie 

You can use [moment](https://momentjs.com/) and [moment-jalaali](https://github.com/jalaali/moment-jalaali#api)
```javascript
import moment from 'moment-jalaali';

// start of current year
const startOfJalaliYear = moment().startOf('jYear').format('jYYYY-jMM-jDD'); //1400-01-01
// end of current year
const endOfJalaliYear = moment().endOf('jYear').format('jYYYY-jMM-jDD'); //1400-12-29

// or given date:
const date = '2020-06-06';
const start = moment(date).startOf('jYear').format('jYYYY-jMM-jDD');
```
