### ISSUE TITLE
use multiple attribute and using with the datetime type

### ISSUE THREAD

**Issue by Niaz-estefaie** [talkhabi/vue-persian-datetime-picker#175]
I need to know If I can have the multiple date picker with the type of date-time.
I have date-time right now but time will be the same for all of the array items of my code

`
<date-picker
      format="jYYYY-jMM-jDD HH:mm:ss"
      v-model="datetime"
      color="#212529"
      type="datetime"
      multiple
      compact-time
      display-format="jMMMM jD"
      clearable 
  />
`

the array would be like this:

datetime = ["1400-06-01 15:04:00", "1400-06-02 15:04:00", "1400-06-10 15:04:00", "1400-06-17 15:04:00"]

As you can see all of the hours are the same.

**Comment by talkhabi** [comment]
Sorry, `range` and `multiple` are only supported for `date` type
