### ISSUE TITLE
Add `max` attribute

### ISSUE THREAD

**Issue by gitgetgotgotten** [talkhabi/vue-persian-datetime-picker#183]
Add `max` attribute  in order to prevent the user to enter numbers more than 12, 24, or 60.

**Comment by talkhabi** [comment]
Anyway, the user can not enter the wrong number for time, do you have a specific reason?

**Comment by gitgetgotgotten** [comment]
Yeah you are right. I hadn't clicked on "تائید" before. Anyway, it could be better to have `min` and `max`.
