### ISSUE TITLE
 rang نمایش تاریخ دیفالت در

### ISSUE THREAD

**Issue by iamammiin** [talkhabi/vue-persian-datetime-picker#184]
سلام. من می‌خوام تاریخی که ذخیره کردم رو وقتی صفحه لود میشه تو رنج نشون بدم ولی فقط قسمت اول رو نشون میده 

<date-picker 
range
clearable
      
name="date_range_show"
      auto-submit
      locale="fa,en"
format="YYYY-MM-DD HH:mm"
      input-class="form-control form-control-solid"
      alt-name="date_range_alt"
      alt-format="YYYY-MM-DD HH:mm"
      value="2021-10-04 00:00 ~ 2021-10-13 23:59"
      display-format="jDD jMMMM jYYYY">
  </date-picker>

**Comment by talkhabi** [comment]
سلام برای استفاده از رنج باید از آرایه استفاده کنید

`<date-picker range :value="['2021-10-04 00:00', '2021-10-13 23:59']" .../>`
