### ISSUE TITLE
using in wordpress

### ISSUE THREAD

**Issue by yasrebi** [talkhabi/vue-persian-datetime-picker#185]
سلام و درود ، پکیج بسیار عالی هستش و روی لاراول خوب کار میکنه 
اما من مشکلم توی استفاده در وردپرس هستش جایی که webpack
نداره و import ها هم ارور میدن ، میخواستم بدونم راه حلی براش دارید ؟ 

با تشکر

**Comment by talkhabi** [comment]
سلام سپاس 
میتونید بصورت استندالون استفاده کنید و فایلهارو بصورت تگ اسکریپت تو هد صفحه قرار بدید

```html
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script src="https://cdn.jsdelivr.net/npm/moment"></script>
<script src="https://cdn.jsdelivr.net/npm/moment-jalaali@0.9.2/build/moment-jalaali.js"></script>
<script src="/dist/vue-persian-datetime-picker.umd.min.js"></script>
```
https://talkhabi.github.io/vue-persian-datetime-picker/guide/installation.html#install-in-a-browser-umd
