### ISSUE TITLE
تغییر استایل تقویم و افزودن روزهای خاص

### ISSUE THREAD

**Issue by MrZMajid** [talkhabi/vue-persian-datetime-picker#19]
با سلام و خسته نباشید و تشکر بابت پکیج خوبی که نوشتید.
یه سوال داشتم در مورد اینکه ما میخوایم توی این پکیج روزهای تعطیل رسمی توی تقویم رو هم علامت دار کنه یعنی مثلا رنگش رو قرمز کنه.و اینکه خودمون یه سری روز ها رو دستی بهش بدیم و این روز ها رو هم به تعطیلاتش اضافه کنه.

یه مورد دیگه هم اینکه چطور میشه یه سری روز های خاص رو بهش بدیم و کاربر نتونه این روز ها رو انتخاب کنه؟

ممنون میشم اگه بتونید منو راهنمایی کنید

**Comment by 1benayatei** [comment]
اتفاقا منم یه همچین چیزی نیاز دارم برای اینکه نتونی یه سری از روز هارو انتخاب بکنه که بصورت ارایه بدیم بهش .

**Comment by MrZMajid** [comment]
ممنون جناب تلخابی. میفرمایید بصورت تقریبی چه مدت طول میکشه این قابلیت رو به این پکیج خیلی خوبتون اضافه کنید؟

**Comment by talkhabi** [comment]
مچکرم
مورد دوم داره کارهای نهاییش انجام میشه و مورد اول بعد از اتمام این ویژگی استارت میخوره

**Comment by MrZMajid** [comment]
متشکرم و پاینده باشید ان شاءالله بتونیم بیشتر از پروژه هاتون بهره ببریم
