### ISSUE TITLE
All the dates and buttons renders as undefined

### ISSUE THREAD

**Issue by alireza0sfr** [talkhabi/vue-persian-datetime-picker#190]
سلام وقت بخیر من در حال کار روی یک پروژه ویو ۲ هستم و میخواستم دیت پیکر اون رو عوض کنم و از پکج شما استفاده کنم ولی وقتی اون رو به پروژه اصلی اضافه کردم تمام تاریخ ها و دکمه ها به صورت تعریف نشده رندر شدند (مانند عکس)
ولی پکیج پراپ ها ها یا وی مدل رو تشخیص میده

برای تست من پکیج شما رو به یک پروژه خام ویو ۲ اضافه کردم و همه چی درست کار میکند
بعد از انجام تست ها متوجه شدم پکیج شما با یکی از پکیج های پروژه ما به مشکل برمیخورد  لیست پکیج ها رو قرار دادم 
با توجه به اسکیل نسبتا بزرگ پروژه امکان حذف و تغییر بسیاری از پکیج ها وجود ندارد
خواستم بدونم حدس شما چی میتونه باشه؟

Hi Dear!
I'm currently working on a vue 2 project and I wanted to change the date picker of the project.
When I added your package to the main project all the buttons and dates were rendered as undefined.
but it rendered v-model and props.
then  I created a new vue-cli project and tested your package there and everything worked fine.
so I began to test different stuff and I found out that some of our dependencies have conflicts with your project and because of the project scale I can't change a lot of dependencies.
Do you happen to know which dependency might conflict with your package?
Thanks a lot in advance

code snippet:

<template>
	<datePicker />
</template>

<script>
import VuePersianDatetimePicker from 'vue-persian-datetime-picker';
export default {
	components: {
		datePicker: VuePersianDatetimePicker
	}
}
</script>

<style>

</style>

[packages.md](https://github.com/talkhabi/vue-persian-datetime-picker/files/7503142/packages.md)
![datepicker](https://user-images.githubusercontent.com/17051188/140891170-e266de91-8eef-42c8-b63b-86aec0aac245.png)
e.

**Comment by rezaei92** [comment]
سلام وقت بخیر من هم دقیقا همین مشکل رو برای استفاده از این پکیج دارم

**Comment by talkhabi** [comment]
سلام دوستان دارم روی این مشکل کار میکنم
بزودی اوکی میشه
فعلا میتونید به این صورت حل کنید:

```js
import VuePersianDatetimePicker from 'vue-persian-datetime-picker/src/VuePersianDatetimePicker'
```

**Comment by talkhabi** [comment]
fixed in `2.10.1`
