### ISSUE TITLE
عدم نمایش دکمه "انصراف"

### ISSUE THREAD

**Issue by Alireza-Sadeghi-0123** [talkhabi/vue-persian-datetime-picker#197]
سلام وقتتون بخیر.
ممنون از کامپوننت خوبتون.
من میخوام دکمه `"انصراف"` رو مخفی کنم، آیا راهی برای این کار وجود داره؟
مورد بعدی هم اینکه `آیا میشه صفحه رو پرسیست کرد` تا کاربر برای بستن مودال مجبور باشه حتماً بر روی دکمه "تأیید" کلیک کنه؟
با تشکر.

**Comment by talkhabi** [comment]
سلام و درود
برای این موارد بهتر نیست از اعتبارسنجی فرم استفاده کرد؟
