### ISSUE TITLE
mouse wheel not work in vuetify-dialog

### ISSUE THREAD

**Issue by webasoo** [talkhabi/vue-persian-datetime-picker#199]
Hello,
On using vue-persian-datetime-picker  in a  v-dialog (vuetify), mouse-wheel doesn't work!

**Comment by talkhabi** [comment]
Hi @webasoo, can you please provide working demo?

**Comment by webasoo** [comment]
of course, how?
 @talkhabi

**Comment by talkhabi** [comment]
Somewhere like [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io/), [codesandbox](https://codesandbox.io/) or ...
