### ISSUE TITLE
Opening date picker programmatically

### ISSUE THREAD

**Issue by M-Barari** [talkhabi/vue-persian-datetime-picker#203]
Hi, how can I open the picker programmatically ? for example on some input focus or on some button click?

**Comment by alireza0sfr** [comment]
Hi there, You can use show prop to control date picker visibility 
Therefore you can bind that prop to a custom button or input or etc

code snipet:
`<template>
	<div>
	 <date-picker :show="isPickerVisible" />
	 <button @click="showPicker">Show Picker</button>
	</div>
</template>

<script>
import DatePicker from 'vue-persian-datetime-picker'
export default {
	components: {
		'date-picker': DatePicker
	},
	data() {
		return {
			isPickerVisible: false,
		}
	},
	methods: {
		showPicker() {
			this.isPickerVisible = true
		},
	}
}
</script>`
