### ISSUE TITLE
خطا در کارکرد تقویم در حالت نمایش سال

### ISSUE THREAD

**Issue by mjfakhr** [talkhabi/vue-persian-datetime-picker#205]
با سلام و احترام
وقتی نوع نمایش تقویم را روی سال تنظیم می کنم ، مطابق نمونه ای که در سایت گذاشته اید کار نمی کند
با کلیک رو سال جدید مقدار نمایشی سال در بالای پنجره تغییر نمی کند
و با کلیک دکمه تایید مقدار مدل عوض نمی شود
لطفا راهنمایی بفرمایید به چه صورتی این خطا را بر طرف کنم 
<date-picker  v-model='year'  type='year' ></date-picker>

**Comment by talkhabi** [comment]
سلام وقتون بخیر
لطفا نمونه کدتون رو اینجا قرار بدید
