### ISSUE TITLE
clearable

### ISSUE THREAD

**Issue by hamedg68** [talkhabi/vue-persian-datetime-picker#206]
clearable property does not show when it is true. why?

**Comment by talkhabi** [comment]
Works for me, [see example](https://jsfiddle.net/talkhabi/8t4uqh6e/).

**Comment by hamedg68** [comment]
but if we link  date-picker to an input clearable icon gone

**Comment by talkhabi** [comment]
Yes, custom-input does not supports this.
So you should make a component and handle it.
