### ISSUE TITLE
مشکل در نسخه ویو 3.2

### ISSUE THREAD

**Issue by vrman** [talkhabi/vue-persian-datetime-picker#208]
با سلام
در نسخه ویو 3.2 وقتی از کامپوننت استفاده میکنم همچین ارروری رو میگیرم، تمام مراحل نصب رو هم درست انجام دادم. 

` <date-picker locale="en,fa" format="YYYY/M/D" />`

`Unhandled error during execution of watcher callback at <DatePicker locale="en,fa" format="YYYY/M/D" > `

**Comment by talkhabi** [comment]
سلام 
همین نسخه رو نصب کردید یا این:

[vue3-persian-datetime-picker](https://github.com/talkhabi/vue3-persian-datetime-picker)

**Comment by vrman** [comment]
نسخه که دادین رو نصب کردین ، مشکل برطرف شد ، ولی تایتل ها سنتر نیستن داخلش ، یه سری مشکلات وجود داره در اون پکیج.

**Comment by talkhabi** [comment]
سلام
من چند مورد تست کردم مشکلی نداشته، احتمال داره از کانفیگ پروژه تون باشه

https://jsfiddle.net/talkhabi/xqc0pfj5/1/

اگر مشکل خاصی از سمت پکیج هست اطلاع بدین رفع کنم
