### ISSUE TITLE
چطور میشه با انتخاب یک ماه روز اول و آخر اون ماه رو دید؟

### ISSUE THREAD

**Issue by Niaz-estefaie** [talkhabi/vue-persian-datetime-picker#209]
سلام و وقت بخیر
میخوام بدونم آیا امکانش هست با انتخاب یک ماه با استفاده ار نوع month
روز اول و آخر اون ماه رو داشته باشیم؟

`
<date-picker v-model="month" type="month" @change="onMonthChange"/>

onMonthChange(event) {
console.log(event);
}
`
آیا اصلا همچین امکانی وجود داره یا نه؟

**Comment by talkhabi** [comment]
سلام ممنون وقتتون بخیر
روز  آخر هرماه بستگی به سال هم داره
مثلا ماه اسفند ممکنه 29 روزه باشه یا 30 روزه

در کل با روش زیر میتونید اول و آخر ماه رو بگیرید
```js
onMonthChange(dateMoment) {
  console.log(dateMoment.endOf('jMonth')); //.format('jYYYY-jMM-jDD')
  console.log(dateMoment.startOf('jMonth'));
}
```
