### ISSUE TITLE
توضیحات برای روزهای هفته و تاریخ های خاص

### ISSUE THREAD

**Issue by Misaghahmadi97** [talkhabi/vue-persian-datetime-picker#210]
سلام
وقتتون به خیر
میخواستم ببینم امکانش هست داخل تقویم ، پایین  تاریخ هایی که نمایش داده میشه ، توضیحات مشخص کرد برای روز های هفته و تاریخ های خاص ؟ برای مثال شنبه ها " مطب از ساعت 16 باز است " یکشنبه ها " مطب از ساعت 8-12 باز است " یا مثلا تاریخ 13 بهمن رو بزنیم " مطب در نوبت صبح و بعد از ظهر باز است " یا توضیحات خاص دیگه ...

**Comment by talkhabi** [comment]
سلام 
بله میتونید از اسلات ها، اتریبیوت ها و یا از ترکیب این دو استفاده کنید:
https://talkhabi.github.io/vue-persian-datetime-picker/guide/highlight.html
