### ISSUE TITLE
min max change in disabled days

### ISSUE THREAD

**Issue by Misaghahmadi97** [talkhabi/vue-persian-datetime-picker#211]
سلام مجدد
موقعی که انتخابگر تو رنج هست ، میشه روزهای غیرفعال رو  انتخاب کرد.
مثلا اگه 1م غیرفعال باشه ، میشه از 12 تا 20 رو انتخاب کرد.
همچنین میخوام کاربر نتونه روز اول و دومش یکی باشه . یعنی موقعی که اولین تاریخ رو انتخاب کرد ، غیرفعال بشه که دیگه انتخاب نکنه برای تاریخ دومش

**Comment by talkhabi** [comment]
سلام 
دقیقا متوجه نشدم مشکلتون چی هست و یوز کیسش چیه.
کاربرد رنج به این صورته که کاربر یک تاریخ شروع و یک تاریخ پایان انتخاب میکنه. تو این حالت فقط تاریخ شروع و پایان چک میشه که غیرفعال نباشه و تاریخ های بین این رنج چک نمیشه (که به صورت منطقی هم باید همینطور باشه).
اگر برای هر روز نیاز دارید این چک اتفاق بیفته بهتره از حالت 
multiple 
استفاده کنید.

**Comment by Misaghahmadi97** [comment]
می‌خوام تقویم رزرو هتل درست کنم
منطقی هست که کاربر موقع انتخاب رنج اقامتش نتونه روزهایی که غیرفعال هستند رو انتخاب کنه
اگه مقدور هست آیدی تلگرام قرار بدید باهاتون در تماس باشم

**Comment by talkhabi** [comment]
آیدی تلگرامم تو پروفایلم هست.
