### ISSUE TITLE
تنظیم مقدار پیش فرض ساعت

### ISSUE THREAD

**Issue by mohammad-zr** [talkhabi/vue-persian-datetime-picker#215]
سلام. وقت بخیر
راهی هست که مقدار پیش فرض ساعت رو وقتی که type=datetime هست تنظیم کنیم؟ یعنی ساعت رو که در حال حاضر ساعت فعلی رو نشون میده همیشه یه مقدار ثابت دیگه ای بشه گذاشت
ممنون

**Comment by talkhabi** [comment]
سلام بله این مورد رو ببینید:
https://talkhabi.github.io/vue-persian-datetime-picker/guide/initial-value.html#startup-initial-value
