### ISSUE TITLE
special times

### ISSUE THREAD

**Issue by mitisa** [talkhabi/vue-persian-datetime-picker#217]
سلام وقتتون بخیر
امکان داره بتونیم زمانهای خاصی رو فعال کنیم و یه سری زمانها غیرفعال باشه؟ منظورم استفاده از max و min نیست مثلا ساعتهای 11 و 12 قابل انتخاب باشن 13 غیرفعال باشه دوباره 14 فعال باشه میتونیم این امکان رو داشته باشیم؟
با تشکر فراوان

**Comment by d4rkr3pt0r** [comment]
@mitisa
```
<date-picker type="time" disable="['/13:(.*)']" />
```

**Comment by mitisa** [comment]
> @mitisa
> 
> ```
> <date-picker type="time" disable="['/13:(.*)']" />
> ```

ممنونم اینو تست کردم بازم همه زمانها قابل انتخاب هست

**Comment by talkhabi** [comment]
سلام 
بله میتونید از رجکس یا تابع استفاده کنید، لطفا این قسمت رو کامل مطالعه بفرمایید:
https://talkhabi.github.io/vue-persian-datetime-picker/guide/disabling.html#disable-dates

```html
<date-picker type="time" :disable="/13:(.*)/" />
```
