### ISSUE TITLE
Day gets unselected when changing month or year

### ISSUE THREAD

**Issue by mrcoder98** [talkhabi/vue-persian-datetime-picker#219]
I use datepicker like this:
`<date-picker simple v-model="userData.birthDate" format="jYYYY/jMM/jDD"
 :initial-value="birthDateMax" :min="birthDateMin" :max="birthDateMax"/>`

When users change month or year,  Day will be unselected everytime

**Comment by talkhabi** [comment]
Please update to last version

https://github.com/talkhabi/vue-persian-datetime-picker#2103-2022-01-06
https://github.com/talkhabi/vue-persian-datetime-picker/issues/207
