### ISSUE TITLE
واکشی مقدار تاریخی که از قبل وارد شده

### ISSUE THREAD

**Issue by KAJOOSH** [talkhabi/vue-persian-datetime-picker#222]
سلام
بنده می خواهم تاریخی که از قبل وارد شده را مقدار آن را به دست بیاورم ..
راهکار آن چیست ..؟ ( هیگونه متودی پیدا نکردم در این زمینه )

**Comment by talkhabi** [comment]
سلام لطفا بیشتر توضیح بدید 
متوجه نشدم چیکار میخواید بکنید

**Comment by KAJOOSH** [comment]
تصور کنید یک فیلد تاریخی داریم که تکمیل شده است
کاربر پس تکمیل چند فیلد دیگر ، سیستم باید باتوجه به آن تاریخی که در چند مرحله ی قبل وارد شده است ، یک بررسی کند ..
سوال اینجاست که چگونه مقدار تاریخی که وارد شده را به دست آورد .. ؟
نکته: من از فریم ورک vue داخل پروژه استفاده نکردم و تنها فقط برای این فریم ورک تاریخ ایمپورت کردم
پروژه من mvc asp net core هستش ..

**Comment by talkhabi** [comment]
میتونید از کانفیگ مربوط به alt فیلد استفاده کنید و با jQuey یا جاوااسکریپت مقدارشو بدست بیارید
