### ISSUE TITLE
عدم نمایش Initial value در Date یا DateTime Picker

### ISSUE THREAD

**Issue by miladganjali** [talkhabi/vue-persian-datetime-picker#237]
سلام تشکر از کتابخانه بسیار کاربردی شما
بعد از ست کردن مقدار Initial value مقدار در Input نمایش داده نمی شود این باگ حتی در صفحه کتابخانه شما در آدرس [این لینک](https://talkhabi.github.io/vue-persian-datetime-picker/guide/initial-value.html#startup-initial-value) مشاهده می گردد.

![datetimePicker-bug](https://user-images.githubusercontent.com/8298544/196349941-8d3aa51b-a5d1-4463-886d-ae1f8eef7693.png)

**Comment by nekooee** [comment]
متأسفانه بنظر میرسه این کتابخونه به حال خودش رها شده و پشتیبانی نداره. منم سوالی پرسیدم ولی الان میبینم اکثر سوالات اخیر هیچ یک پاسخی دریافت نکردند...
احتمالا باید از کتابخانه دیگری استفاده کنیم

**Comment by drupalshift** [comment]
@miladganjali 
دوست عزیز ببین initial-value یعنی مقدار اولیه ای که هنگام باز شدن تقویم نمایش داده میشه 
برای ست کردن مقدار باید value رو ست کنید اگر میخواهید درون فیلد مقدار اولیه بزارید 

![image](https://github.com/talkhabi/vue-persian-datetime-picker/assets/9895625/c01d4110-3444-41bf-8f88-b2b3458cc37e)

**Comment by mehdicodecom** [comment]
![Captusdsdre](https://github.com/talkhabi/vue-persian-datetime-picker/assets/129201955/93fa6f5a-cc82-488b-87a0-7517fc31fa0b)
من v-model رو دیتاش از API دارم میگیرم و پر هستش ولی همچنان نمایش نمیده روش

**Comment by parsidev** [comment]
سلام. وقت بخیر
این مورد وقتی که از customInput استفاده میکنیم. کار نمیکنه

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <script src="https://cdn.jsdelivr.net/npm/vue@2.7.16/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/moment"></script>
    <script src="https://cdn.jsdelivr.net/npm/moment-jalaali@0.9.2/build/moment-jalaali.js"></script>
    <script src="./vue-persian-datetime-picker.umd.min.js"></script>
</head>
<body>
<div id="app">
    <input name="test_picker" id="test_picker" />
    <date-picker v-model="date" format="jYYYY/jMM/jDD" value="1403/11/27" custom-input="#test_picker" />
</div>
<script>
    var app = new Vue({
        el: '#app',
        data: {
            date: '1403/11/27'
        },
        components: {
            DatePicker: VuePersianDatetimePicker
        }
    });
</script>
</body>
</html>
```
