### ISSUE TITLE
ایجاد تقویم inline

### ISSUE THREAD

**Issue by arbabi2010** [talkhabi/vue-persian-datetime-picker#24]
سلام. من میخام این تقویم رو به صورت inline نشون بدم
چطور این کار امکان پذیره؟ توی نمونه ها موردی براش وجود نداره

**Comment by arbabi2010** [comment]
@talkhabi خیلی ممنونم
اما اون چیزی که من میخام منظورم این نیست
میخام از همون اول بدون اینکه روی اینپوتی بزنم باز باشه  خود تقویم

**Comment by talkhabi** [comment]
علاوه بر کارهای بالا این تنظیمات راهم انجام بدهید
```
<date-picker  :show="show"  .... ></date-picker>
<script>
    export default {
        data() {
            return {
                show: false
            }
        },
        mounted() {
            this.show = true;
        }
    }
</script>
```
فعلا از این استفاده کنید تا در ورژن های بعدی این قابلیت اضافه شود.
