### ISSUE TITLE
استفاده در پروژه‌ی ام.وی.سی

### ISSUE THREAD

**Issue by hrsh** [talkhabi/vue-persian-datetime-picker#25]
سلام و تشکر بابت ارائه‌ی این کمپوننت.
من در یک پروژه‌ی ام.وی.سی از این کمپوننت استفاده می‌کنم. دو پرسش دارم:
اعداد به صورت لاتین نمایش داده می‌شوند. مثلا بجای ۱۳۹۷ نوشته می‌شود 1397.
آیا این امکان هست که نمایش انتخاب تقویم یا ساعت را در یک رویداد کلیک، مثلا یک دکمه قرار داد؟
ممنون از راهنمایی

**Comment by talkhabi** [comment]
سلام مچکر
اعداد باید لاتین باشن تا بشه روی اونها محاسبات انجام داد
در نمایش اعداد فارسی ما فقط از فونت فارسی استفاده میکنیم که اعداد لاتین رو هم فارسی نمایش میده

سوال دوم هم بله امکانش هست، نمونه مثالش در داکیومنت و دمو هست.

**Comment by talkhabi** [comment]
```
<date-picker  :show="show"  @close="show=false"></date-picker>
<button  type="button" @click="show=true"> Show Datepicker</button>
```

**Comment by hrsh** [comment]
من از فونت فارسی ایران‌سنس استفاده می‌کنم و اعداد فارسی نمایش داده نمی‌شوند.
با توجه به اینکه علامت 
`@`
در ام.وی.سی به شکلی که گفته‌اید امکان پذیر نیست، چه پیشنهاد می‌دهید؟

```
<date-picker  :show="show"  @@close="show=false"></date-picker>
<button  type="button" @@click="show=true"> Show Datepicker</button>
```
یا
```
<date-picker  :show="show"  onclose="show=false"></date-picker>
<button  type="button" onclick="show=true"> Show Datepicker</button>
```

**Comment by talkhabi** [comment]
فونت ایران سنس هم با اعداد لاتین و هم  با اعداد فارسی وجود دارد، شما باید فونت  با اعداد فارسی پیدا کنید.

```
<date-picker  :show="show"  v-on:close="show=false"></date-picker>
<button  type="button" v-on:click="show=true"> Show Datepicker</button>
```
