### ISSUE TITLE
Timezone Option 

### ISSUE THREAD

**Issue by m-alikhani** [talkhabi/vue-persian-datetime-picker#33]
سلام
لطفا در صورت امکان این آپشن رو قرار بدید

**Comment by talkhabi** [comment]
سلام @m-alikhani 
بنده عذرخواهی میکنم که این مورد رو فراموش کرده بودم
امکانش هست بیشتر درمورد این آپشن توضیح بدید که به چه صورت باید باشه ؟

**Comment by m-alikhani** [comment]
سلام @talkhabi 
ببینید، ما تاریخ رو بدون تایم زون تو بانک اطلاعات ذخیره میکنیم. چون از کشور های مختلفی کاربر داریم. یعنی همیشه تاریخ و ساعت رو به صورت UTC ذخیره میکنیم. موقع نمایش با توجه به تایم زون کاربر اطلاعات رو نمایش میدیم. الآن خودمون قبل از اینکه تاریخ و ساعت رو به ابزار شما بدیم تایم زون رو بهش اضافه میکنیم. همچنین موقعی که می خوایم اطلاعات رو ذخیره کنیم بازم تایم زون رو ازش کم میکنیم. 
به طور خلاصه اینکه بشه تاریخ و ساعت رو همیشه به صورت UTC به ابزار داد و موقع نمایش نسبت به تایم زون انتخاب شده نمایش بده.

**Comment by talkhabi** [comment]
ممنون از توضیحاتتون @m-alikhani 
خب اینطور که من متوجه شدم باید یه پراپ برای این درنظر بگیریم که یه مقدار استرینگ یا بولین بگیره برای تایمزون

اگر بولین بود تایمزون کاربر اتوماتیک تشخیص داده بشه و اگر استرینگ بود طبق اون کم و زیاد بشه
این اوکی هست؟

**Comment by m-alikhani** [comment]
@talkhabi عالی میشه اینطوری

**Comment by hbsoftco** [comment]
Has this feature been added now?

**Comment by talkhabi** [comment]
@hbsoftco 
Yes
https://talkhabi.github.io/vue-persian-datetime-picker/#/timezone
