### ISSUE TITLE
 Doesn't watch on :min and :max properties!!

### ISSUE THREAD

**Issue by HamidOsouli** [talkhabi/vue-persian-datetime-picker#34]
Hi. great package. I put **:min** or **:max** on date picker and it works well but when I reset the max or min value on my component, max and min wont change and date picker doesn't watch for these properties so I still have boundaries for choosing the date
Great work by the way :)

**Comment by talkhabi** [comment]
Hi, thank you!
Actually there is watcher for **min** and **max**: [see](https://github.com/talkhabi/vue-persian-datetime-picker/blob/ec439bf00a7a42a0e39f008768e5ec1892f3d40e/src/picker/VuePersianDatetimePicker.vue#L977).

But the problem will occur when we try to set `min = '' or min = null`.
You can use `min = '1200/01/01' or max = '1500/01/01'` (setting min and max for long period).
And I'll fix this in next version.
