### ISSUE TITLE
Is there anyway to clear date inside the input?

### ISSUE THREAD

**Issue by Daniyal-Javani** [talkhabi/vue-persian-datetime-picker#37]
I'm looking for a way to clear the date inside the filled input like a button. Seems there are a props like `clear-button`  in other projects:
https://github.com/charliekassel/vuejs-datepicker#available-props

**Comment by talkhabi** [comment]
You can clear the date like this: 
```
<date-picker v-model="date"></date-picker>
<button @click="date=''">Clear</button>
...
export default {
  data() {
    return { date: '' }
  }
}
```
