### ISSUE TITLE
add new option Range select 

### ISSUE THREAD

**Issue by davodaslanifakor** [talkhabi/vue-persian-datetime-picker#4]
hi 
please add new option
Range select by drag or custom day select

**Comment by talkhabi** [comment]
آقا منظورتو دقیق تر میفرمایی؟

**Comment by talkhabi** [comment]
این خودش تشکیل شده از دوتا 
datepicker
که در حال حاضر ما نمیتونیم همچین قابلیتی اضافه کنیم
ولی شما خودت میتونی یه کامپوننت بسازی که از دوتا پیکر استفاده کنی و همچنین از قابلیت های زیر برای محدود کردن 
min, max

**Comment by AltiumWilliam** [comment]
سلام
قبل از هر چیز باید ازتون تشکر کنم بابت این کامپوننت عالی که ساختید. یعنی آدم هر آنچه از یک چنین کامپوننت تاریخ نیاز داره را شامل میشه.
من با پیشنهاد این دوستمان موافقم، اگر بتوان با یک پیکر یک رنج را انتخاب کرد عالی میشه، در حال حاضر من از دو پیکر استفاده میکنم که یکی تاریخ شروع و دیگری تاریخ پایان هست. اگر این دو یکی شود هم در فضا صفحه صرفه جویی میشه هم دیگه خیالم برنامه نویس از برخی والیدیشن ها راحت میشه (مثلا تاریخ شروع بعد پایان نباشه و اینکه هر دو تاریخ درج شده باشه). من اون کامپوننتی که در کامنتهای بالایی استفاده را نگاه کردم، ایده اون را میشه در این کامپوننت هم بکار برد. با کلیک اول تاریخ شروع انتخاب شود و با کلیک دوم (میشه راست کلیک هم باشه) تاریخ پایان انتخاب بشه و در نهایت خروجی بازه تاریخ شود یا یک آرایه از دو تاریخ. ببخشیدکه خیلی طولانی نوشتم
