### ISSUE TITLE
چطور میشه بعد کاربر بعد اینکه روی تایید کلیک کرد ساعت باز بشه؟

### ISSUE THREAD

**Issue by hamedbaftam** [talkhabi/vue-persian-datetime-picker#41]
چطور میشه بعد کاربر بعد اینکه روی تایید کلیک کرد ساعت باز بشه؟ چون واقعا طبق فید بک هایی که گرفتم کاربرا  بیشتر روی تاریخ کلیک میکنن . ولی این کتابخونه برای تعیین ساعت باید روی اون تاریخ کلیک کرد

**Comment by talkhabi** [comment]
بله حق با شماست، در ورژن های بعدی این مورد اصلاح میشه
