### ISSUE TITLE
عدم نمایش alt field بعد از انتخاب تاریخ

### ISSUE THREAD

**Issue by webafra** [talkhabi/vue-persian-datetime-picker#48]
با سلام و احترام خدمت شما جناب آقای تلخابی بزرگوار ،‌بابت پکیج فوق العاده کاربردیتون ممنونم

یک موردی رو من واقعا متوجه نشدم و نتونستم پیاده کنم
من میخوام یه فیلد داشته باشم که فرمت ورودی که کاربر انتخاب میکنه به شکل شمسی یا میلادی ( با یه متغییر این کارو انجام دادم ) باشه ولی تو متغییری که دارم درون دیتا میخوام میلادی ثبت بشه 

نمیدونم این حالت شدنی هست یا نه 
چیزی که به فکرم رسید اینه که : 
خواستم از alt برای این کار استفاده کنم که متاسفانه اونم کار نمیکنه ( یعنی نتونستم بفهمم چرا alt رو نمایش نمیده )
در واقع با کد زیر ، آلت نمایش داده نمیشه : 
`
<date-picker
    v-model="date"
    alt-name="date_alt"
    alt-format="YYYY-MM-DD HH:mm:ss">
</date-picker>
`

ممنون میشم راهنماییم کنید

**Comment by talkhabi** [comment]
سلام روز بخیر، ممنون و متشکر دوست عزیز
در مورد Alt field بگم که این فیلد مخفی هست و دیده نمیشه برای مواقعی که میخوایم فرم رو سریالایز کنیم و بفرستیم به کار میاد.
اما برای کاری که میخواید انجام بدید راه حلش به این صورت هست: 

```html
<template>
    <button @click="changeDisplayFormat">Change format</button>
    <date-picker
            v-model="date"
            format="YYYY-MM-DD HH:mm:ss"
            :display-format="displayFormat">
    </date-picker>
</template>

<script>
export default {
    data() {
        return {
            date: '2019-03-16 10:13:00',
            displayFormat: 'jYYYY/jMM/jDD'
        }
    },
    methods: {
        changeDisplayFormat() {
            // change the display format
            // ...
            this.displayFormat = 'YYYY/MM/DD';
            // or
            //this.displayFormat = 'jYYYY/jMM/jDD';
        }
    }
}
</script>
```
