### ISSUE TITLE
Please add language support for Chinese

### ISSUE THREAD

**Issue by WangNingning1994** [talkhabi/vue-persian-datetime-picker#49]

**Comment by talkhabi** [comment]
Hi @WangNingning1994 
There is many datepickers that supports Chinese, why this one :) !?

**Comment by WangNingning1994** [comment]
Hi @talkhabi beause we need a Vue component that supports both English and Chinese, and supports date format like YYYY-MM-DD HH:mm, this one is suitable except for lacking language support for Chinese.

**Comment by talkhabi** [comment]
It's not a good idea at all to use this plugin because we load the `moment-jalaali` and it calculates the dates via a different algorithm.
You should use [vuejs-datepicker](https://www.npmjs.com/package/vuejs-datepicker/)
