### ISSUE TITLE
باگ نمایش تاریخ

### ISSUE THREAD

**Issue by Ham3D** [talkhabi/vue-persian-datetime-picker#5]
با انتخاب تنظیمات پیشفرض با کلیک روی تاریخ مورد نظر این تاریخ انتخاب میشه:
۰۰۰۰/۰۱/۰۱
اگر تاریخ رو دوباره انتخاب کنی باز هم همین مقدار نمایش داده میشه.
در هنگام انخاب برای بار سوم این دفعه مقادیر درست نمایش داده میشن .
![screen shot 1397-01-11 at 10 03 42 pm](https://user-images.githubusercontent.com/3233668/38165845-66c6fe08-352f-11e8-8af7-4ee41dce6270.png)
با اینکه نمایش تاریخ به این نحو هست اما در لاگ ها میشه دید که تاریخ درست انتخاب میشه.
مشکل زمانی پیش می آد که درکامپوننت هایی همزمان از مومنت و قابلیت نمایش فارسی اعداد استفاده کنیم 
این اوکی هست :
 let moment = require("moment-jalaali");
return moment(date, 'jYYYY/jM/jD HH:mm').format('YYYY-M-D HH:mm:ss');
اما اگر این خط رو اضافه کنیم مشکلی که در بالا  گفتم به وجود می آد
moment.loadPersian({usePersianDigits: true})

**Comment by talkhabi** [comment]
به جای استفاده از اعداد فارسی از فونت فارسی استفاده کنید چون اعداد فارسی محاسبه نمیشن
