### ISSUE TITLE
پیشنهاد اضافه کردن امکانات بیشتر

### ISSUE THREAD

**Issue by marmulack** [talkhabi/vue-persian-datetime-picker#51]
سلام آقای @talkhabi 
با تشکر از کار خوب و زیباتون

 پیشنهاد میکنم ابزاری برای انتخاب یک رنج زمان یا تاریخ (شروع - پایان) رو هم اضافه کنید.

**Comment by talkhabi** [comment]
سلام
متشکر و ممنون
با توجه به زیر ساخت پروژه فعلی و از طرفی مشغله های کاری موجود، اضافه کردن چنین فیچر هایی کار زمان بر و پیچیده ای است.
اما در صورت امکان و فرصت تا حدی انجام خواهد شد.
موفق باشید
