### ISSUE TITLE
اشتباه در انتخاب تاریخ - selected class

### ISSUE THREAD

**Issue by javad89198103** [talkhabi/vue-persian-datetime-picker#53]
زمانی که تاریخ پیشفرض تقویم روی "1371/01/03" هست، تقویم در حالت نمایش روز فعال رو "2" انتخاب میکنه.

> از ویژگی element="custom-input" استفاده کردم.

انگار دکمه 3 انتخاب شده، چون کلیک هم نمیشه. انگار کلاس "selected" بهش داده نشده. 

![Screenshot (7)](https://user-images.githubusercontent.com/29368388/57013338-4f7f3200-6c20-11e9-9b85-52c9135fbdb6.jpg)

**Comment by talkhabi** [comment]
این مورد در حال بررسی هست
بخاطر تغییر ساعت ها در فصل بهار و پاییز چنین مشکلی رخ میده

**Comment by javad89198103** [comment]
مرسی از رسیدگیتون
