### ISSUE TITLE
custom input not working

### ISSUE THREAD

**Issue by koosha72** [talkhabi/vue-persian-datetime-picker#54]
I've used exactly the same markup as the documentation:
```
<input
    type="text"
    class="form-control form-control-lg"
    v-model="date"
    id="my-custom-input"
    placeholder="select date">

<date-picker
    v-model="date"
    format="jYYYY/jMM/jDD"
    element="my-custom-input">
</date-picker>
```
when I click on input the picker shows up but when I choose a date the text inside the input doesn't change.
I've noticed that I've this error in the browser console:

> [Vue warn]: Property or method "date" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

whenever I choose a date the error shows up again.
I'm using laravel and this is how I load the component inside app.js:

```
import VuePersianDatetimePicker from 'vue-persian-datetime-picker';

Vue.component('date-picker', VuePersianDatetimePicker);
```

hope I've given enough information.
thanks in advance

**Comment by talkhabi** [comment]
You should to define the `date` in data like this:

```javascript
import VuePersianDatetimePicker from 'vue-persian-datetime-picker'
export default {
    data(){
        return {
            date: ''  // <--- here 
        }
    },
    components: {
        datePicker: VuePersianDatetimePicker
    }
}
```
