### ISSUE TITLE
v-model does not update on keyup when the field is editable

### ISSUE THREAD

**Issue by imami** [talkhabi/vue-persian-datetime-picker#57]
When the field is editable, the binded model is not updated automatically on input's keyup event.
it only updated on blur event.

**Comment by talkhabi** [comment]
@imami this is normal behavior, because when the user is typing, date is still not valid. 
We have to wait to complete the user's typing, then check it out.

**Comment by talkhabi** [comment]
closed due to inactivity

**Comment by serfend** [comment]
the model-value still not updated even if the user have input the date-value, and moved the mouse out of the zone.
according to my test , i find that it can worked when the user input the date-value in the second times.
```html
<DatetimePicker
      v-model="formApply.StampLeave"
      type="datetime"
      :color="theme"
      format="YYYY-MM-DD HH:mm:ss"
      editable
      locale="zh-cn"
      :locale-config="localeConfig"
    />
```
![image](https://user-images.githubusercontent.com/20139227/122179679-54fc6c80-ceba-11eb-9fa9-c9964ee6a32f.png)
