### ISSUE TITLE
نمایش تاریخ اشتباه

### ISSUE THREAD

**Issue by rezak997** [talkhabi/vue-persian-datetime-picker#59]
وقتی تاریخ 1365/06/31 انتخاب میشه یا از سمت سرور برای نمایش به کامپوننت مقدار دهی میشه تاریخ امروز نمایش داده میشه به جای تاریخ اعلام شده

**Comment by talkhabi** [comment]
سلام برادر
اینو تست کردم درست بود.
آیا شما از آخرین ورژن استفاده میکنید؟

**Comment by talkhabi** [comment]
Closed due to inactivity
