### ISSUE TITLE
Problem With Style

### ISSUE THREAD

**Issue by nimadeve** [talkhabi/vue-persian-datetime-picker#62]
datePicker kheili khobiye ama ba kochek tarin taghir dar css site rosh tasir mizareva hame chiz mirize beham va bayad koli vaght gozasht joft jor kard

**Comment by talkhabi** [comment]
Hi @nimadeve Ok,
Do you have any suggestion for this problem?

**Comment by talkhabi** [comment]
closed due to inactivity
