### ISSUE TITLE
نمایش اعداد فارسی در تقویم فارسی حتی با تنظیم فونت انجام نمیشود

### ISSUE THREAD

**Issue by claymore07** [talkhabi/vue-persian-datetime-picker#63]
سلام 
در نمایش اعداد فارسی به مشکل برخوردم. 
 زبان کل صفحه فارسی گذاشتم، فونت تمام احزا صفحه رو ایران سنس گذاشتم. ولی در انتخاب گر تقویم بازم 
اعداد انگلیسی هستن سی اس اس زیر هم نمونه اش است. جالب اینه که در داخل اینپوت اعداد رو قارسی نشون می ده اما در انتخاب گر تقویم انگلیسی!
`
body, html, h1, h2, h3, h4, h5, h6,input, textarea, body, table, tr, td, p, a, select {
    font-family: IRANSans, sans-serif !important;
}` 

`.vpd-wrapper {
    font-family: IRANSans,Tahoma,sans-serif !important;
}
`
فونت های ایران سنس مربوط به اعداد هم در سی اس اس موجود هستن و هر جای دیگه اعداد فارسی هست 
با فونت درست نمایش میده
با تشکر از زحمات و راهنمایی تون

**Comment by claymore07** [comment]
راه حل رو پیدا کردم

11:22 AM

در تقویم فارسی vue Perisan date picker باید ابتدا فونت های اعداد و فونت معمولی IRANSans را به css اضافه کنیم و سپس  در css کدهای زیر را اضافه کنیم
```
.vpd-wrapper {
    font-family: IRANSans,Tahoma,sans-serif;

}
.vpd-dir-ltr .vpd-content {
    text-align: left;
    font-family: sans-serif !important;
}
```

**Comment by kamisaberi** [comment]
از فونت wazir استفاده کنین. به نظر من از ایران سنس زیباتره و هم بصورت خودکار اعداد فارسی داره . از فونت لاتین roboto هم استفاده کرده
