### ISSUE TITLE
how to change value using javascript/jquery

### ISSUE THREAD

**Issue by MostafaNobaghi** [talkhabi/vue-persian-datetime-picker#64]
I using this library in a laravel project, not a vue project.  i want to pass a gregorian date to datepicker using jquery and datepicker show the new date. how can i do that?
and how can i empty the datepicker?

**Comment by talkhabi** [comment]
Hi @MostafaNobaghi 
I don't know how you used it, I suggest the following solution:
```html
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script src="https://cdn.jsdelivr.net/npm/moment"></script>
<script src="https://cdn.jsdelivr.net/npm/moment-jalaali@0.7.4/build/moment-jalaali.js"></script>
<script src="dist/vue-persian-datetime-picker-browser.js"></script>
<div id="app">
  <date-picker v-model="date"></date-picker>
</div>
<script>
  var app = new Vue({
    el: '#app',
    data: {
      date: '1398/03/01'
    },
    components: {
      DatePicker: VuePersianDatetimePicker
    }
  });
</script>
<script>
$(document).on('click', 'somewhere', function() {
  app.date = '1398/04/01'
  // app.date = moment().format('jYYYY/jMM/jDD') // means today
  // app.date = ''
})
</script>
```
### [**Example fiddle**](https://jsfiddle.net/talkhabi/mfzk031j/)

**Comment by MostafaNobaghi** [comment]
> Hi @MostafaNobaghi
> I don't know how you used it, I suggest the following solution:
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/vue"></script>
> <script src="https://cdn.jsdelivr.net/npm/moment"></script>
> <script src="https://cdn.jsdelivr.net/npm/moment-jalaali@0.7.4/build/moment-jalaali.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/vue-persian-datetime-picker@2.0.1/dist/vue-persian-datetime-picker-browser.js"></script>
> <div id="app">
>   <date-picker v-model="date"></date-picker>
> </div>
> <script>
>   var app = new Vue({
>     el: '#app',
>     data: {
>       date: '1398/03/01'
>     },
>     components: {
>       DatePicker: VuePersianDatetimePicker
>     }
>   });
> </script>
> <script>
> $(document).on('click', 'somewhere', function() {
>   app.date = '1398/04/01'
>   // app.date = moment().format('jYYYY/jMM/jDD') // means today
>   // app.date = ''
> })
> </script>
> ```
> 
> ### [**Example fiddle**](https://jsfiddle.net/talkhabi/mfzk031j/)

thak you for your response and your great package

**Comment by masoodmrx** [comment]
سلام چطوری میشه توی ورژن
vue3
این کار را انجام داد
