### ISSUE TITLE
In editable mode, I want to open date-picker, without click on icon

### ISSUE THREAD

**Issue by essivision** [talkhabi/vue-persian-datetime-picker#66]
Hi,
This option is good for me:
[https://talkhabi.github.io/vue-persian-datetime-picker/#/editable](https://talkhabi.github.io/vue-persian-datetime-picker/#/editable) 

but I want to open date-picker when cursor focus on input, like this:
[https://codepen.io/essvision/pen/vqgNzZ](https://codepen.io/essvision/pen/vqgNzZ)

What should I do? If you don't have any solution, please add this feature in next release.

Thanks

**Comment by talkhabi** [comment]
Did you tried [this](https://talkhabi.github.io/vue-persian-datetime-picker/#/custom-editable-input)?

```html
<button @click="show = !show">Show Datepicker</button>
<input
    type="text"
    class="form-control is-editable"
    placeholder="YYYY/MM/DD"
    v-model="date"
    id="my-custom-editable-input"
    @focus="show = true"
/>
<date-picker
    v-model="date"
    format="jYYYY/jMM/jDD"
    element="my-custom-editable-input"
    :editable="true"
    :show="show"
    @close="show = false"
/>
```
```js
data() {
    return{
        date: '',
        show: false
    }
}
```
