### ISSUE TITLE
نمایش تایم پیکر در مودال

### ISSUE THREAD

**Issue by Ham3D** [talkhabi/vue-persian-datetime-picker#7]
با توجه به اینکه تایم پیکر خودش رو به پرنت متصل میکنه اگر در مودال استفاده بشه درست نمایش داده نمیشه .
راه حل اینه که پراپرتی زیر رو هم تعریف کنید .
append_to
که بتونیم در مودال هم ازش استفاده کنیم

**Comment by talkhabi** [comment]
میتونید از قابلیت 
Custom input element
کنید و کامپوننت رو بزارید خارج از مودال، خود فیلد رو بزارید داخل مودال

**Comment by talkhabi** [comment]
در ورژن 1.1.1 از این ویژگی میتوانید استفاده کنید
