### ISSUE TITLE
نوع سال و ماه

### ISSUE THREAD

**Issue by MahdadGhasemian** [talkhabi/vue-persian-datetime-picker#70]
سلام
ضمن تشکر از زحماتتون

لطفا در صورت امکان به انواع 
(datetime , time , year and month) 
نوع دیگری برای انتخاب سال و ماه پشت سرهم اضافه کنید.

ممنون

**Comment by talkhabi** [comment]
سلام، ممنونم ایده خوبی هست
در ورژن های بعد اضافه خواهد شد
