### ISSUE TITLE
استفاده همزمان از localization و custom input

### ISSUE THREAD

**Issue by esfahanweb** [talkhabi/vue-persian-datetime-picker#71]
<div dir="rtl">
ضمن عرض سلام

من به تازگی با کامپوننت بسیار خوبتون آشنا شدم

موردی که برخوردم اینه که هنگام استفاده همزمان از localization و custom input فرمت تاریخ رو باید حتما ست کرد.

```html
<date-picker date-picker locale="fa,en" :locale-config="{
    fa: {
      displayFormat: 'jYYYY-jMM-jDD',
      lang: { label: 'شمسی' }
    },
    en: {
      displayFormat: 'YYYY-MM-DD',
      lang: { label: 'Gregorian' }
    }
  }" element="airsearchformdomestic-departure" v-model="date"></date-picker>
````

و در `input` مربوطه هم `v-model="date"` هست.
در این حالت با تغییر زبان و انتخاب روز همیشه فرمت پیشفرض رو در `input` نمایش میده و در واقع مقل اینکه `displayFormat` رو از زبان انتخاب شده نمیخونه
</div>

**Comment by talkhabi** [comment]
سلام، بسیار ممنون
گزینه displayFormat برای custom input قابل استفاده نیست
برای این کار شما باید از computed ها استفاده کنید و فرمت نمایش اون اینپوت رو دستی تغییر بدید.

**Comment by esfahanweb** [comment]
بسیار عالی
ممنون از راهنماییتون
