### ISSUE TITLE
مشکلات

### ISSUE THREAD

**Issue by hamid-r-shakibi** [talkhabi/vue-persian-datetime-picker#72]
<div style="direction:rtl;text-align:right">سلام.من از پکیجتون استفاده کردم ولی بعد اینکه کلیک میکنم هیچ کاری نمیکنه.فقط روی اسم ماه یا سال زدنی اونارو میشه تغییر داد.تایید و انصراف و اکنون و حتی دکمه های فلش که ماه رو تغییر میدن کار نمیکنه.درضمن مارجین قسمتی که تاریخ رو نشون میده زیاده و اول تاریخ نشون داده نمیشه
<br/>

![image](https://user-images.githubusercontent.com/34796399/61875587-35dc4680-af00-11e9-8d8d-3b87055095a4.png)

و درضمن مقداری که این به مدل که میدیم بهش میده چی هستش؟تایم استمپ؟ و مسئله دیگه ای که هست اینه که صفحه داکیومنت که گذاشتین وجود نداره

**Comment by talkhabi** [comment]
Please provide a sample code in [fiddle](https://jsfiddle.net/) or [codepen](https://codepen.io/) or any other websites.

**Comment by ayylin** [comment]
سلام
متاسفانه استفاده از تایم استمپ در حالت Custom input کار نمیکنه.
ممنون
