### ISSUE TITLE
کاهش قابل توجه اندازه 

### ISSUE THREAD

**Issue by hassan-jahan** [talkhabi/vue-persian-datetime-picker#73]
سلام

آقا کارتون عالیه. دستت درد نکنه تنها نقص به نظرم استفاده از مومنت هست که حتی بدون لوکال هم بیش از اندازه بزرگ و کنده

.احتمالا بشه با عوض کردن چند خطر مومنت رو با دی جی اس عوض کنید
چون توابع و مشخصاتشون یکی هست و نسخه جلالی هم داره:

https://github.com/iamkun/dayjs
https://github.com/alibaba-aero/jalaliday
https://github.com/iamkun/dayjs

**Comment by talkhabi** [comment]
سلام @hassan-jahan 
ممنون از شما حتما بررسی خواهد شد

**Comment by hassan-jahan** [comment]
ممنونم

من با استفاده از این دستورالعمل یه مقدار جلو رفتم ولی برای یکی از توابع گیرکردم:
https://github.com/iamkun/dayjs/issues/529

**Comment by talkhabi** [comment]
این پکیج سایزش کم هست اما برای استفاده از هر قسمت باید ایمپورت بشه
و ممکنه در آخر همون سایز بشه
از طرفی مومنت در اکثر پروژه ها استفاده میشه و کم پیش میاد که کسی فقط بخاطر دیتپیکر بخواد نصبش کنه (حداقل برای منکه اینطور بوده یعنی همه جای پروژه ها مومنت استفاده کردم)

اگر اکثر کاربرها نظرشون برای جایگزین کردن مومنت بود، بعد برای اصلاح این مورد یه فکری میکنیم
