### ISSUE TITLE
how to change min and max at runtime 

### ISSUE THREAD

**Issue by kamisaberi** [talkhabi/vue-persian-datetime-picker#74]
hi. i want to change min and max attributes at runtime , how should i do that ?

**Comment by talkhabi** [comment]
Hi @kamisaberi see [this fiddle example](https://jsfiddle.net/talkhabi/ugwm0ht7/)

**Comment by kamisaberi** [comment]
thanks . but i prefer to use jquery to do that .

**Comment by kamisaberi** [comment]
by any problem i have in my bt4 template i cant use start end solution . i should change end min attribute by myself

**Comment by talkhabi** [comment]
Okay, You can't change the attribute manually but there is a way like this: #64

**Comment by kamisaberi** [comment]
i used it , but i only can change date and cant change min or max

**Comment by kamisaberi** [comment]
i found a way that works 


        var start_date = new Vue({
            el: '#start-date',
            data: {
                date: moment().format('jYYYY/jMM/jDD'),
                today: moment().format('jYYYY/jMM/jDD'),
            },
            components: {
                DatePicker: VuePersianDatetimePicker
            },
            methods: {
                onChange(picker) {

                    // alert(moment(picker).format('jYYYY/jMM/jDD'));
                    end_date.date = picker;
                    // end_min = picker;
                    // $("#btn-test").trigger('click');
                    // min= picker;
                    // end_date.setMinMax({'min': moment(picker).format('jYYYY/jMM/jDD')});
                    end_date.min=moment(picker).format('jYYYY/jMM/jDD');
                    end_date.update();
                    // alert(picker.format('yyyy'));
                }
            }
        });


        var end_date = new Vue({
            el: '#end-date',
            data: {
                date: moment().format('jYYYY/jMM/jDD'),
                today: moment().format('jYYYY/jMM/jDD'),
            },
            components: {
                DatePicker: VuePersianDatetimePicker
            },
            methods: {
                onChange1(picker) {
                    alert(picker.value);
                }
            }
        });

**Comment by kamisaberi** [comment]
after change that min or max property at runtime just need to call update method

**Comment by kamisaberi** [comment]
thanks @talkhabi   . its awesome library
