### ISSUE TITLE
مشکل جدی در انتخاب تاریخ

### ISSUE THREAD

**Issue by K1-Aria** [talkhabi/vue-persian-datetime-picker#75]
با سلام
این پکیج یک مشکل جدی داره و اونم فقط در موقعی هست که
v-model
به فیلد اضافه شده باشه و در موقعی که سعی میکنیم دقیقا فردای روز فعلی رو انتخاب کنیم روز فعلی رو انتخاب میکنه و نمایش میده
و باید دوبار فردای روز فعلی رو انتخاب کرد تا درست بشه

**Comment by talkhabi** [comment]
سلام لطفا اگه ممکنه یه نمونه بسازید مثل این لینک:

https://jsfiddle.net/talkhabi/ugwm0ht7/

**Comment by K1-Aria** [comment]
*با سلام*
بله این مشکلو داشت و از طریق custom input حلش کردم یعنی یه button گذاشتم و
input خودم رو گذاشمت و حالا با v-model خوب کار میکنه

فقط یه سوال
در حالت قبل (وقتی فقط تگ date-picker بود) موقعی که تاریخ میلادی رو داخلش
init میکردم خودش اتومات شمسی رو نشون میداد
اما در این حالت که custom input استفاده کردم دقیقا همون میلادی ای که توی
v-model لود کردم رو نشون میده
آیا تنظیماتی داره؟؟

**Comment by talkhabi** [comment]
فعلا این دوتا آپشن باهم دیگه قابل استفاده نیست متاسفانه

**Comment by K1-Aria** [comment]
نه هیچ مشکلی نیست
داخل کنترلر با پکیج morilog به شمسی تبدیلش میکنم
ممنون از پکیج خوبتون

**Comment by talkhabi** [comment]
خواهش میکنم، موفق باشید
