### ISSUE TITLE
استفاده از رنج تاریخ

### ISSUE THREAD

**Issue by webafra** [talkhabi/vue-persian-datetime-picker#76]
با سلام و تشکر بابت پیاده سازی این پکیج خیلی کاربردی

آیا امکانش هست قابلیت انتخاب رنج تاریخ رو هم به پکیج اضافه کنید ؟
طوری که بشه یه بازه شروع و پایان رو انتخاب کرد ؟

اگر بشه برای انتخاب یه محدودیتی هم گذاشت عالی میشه
مثلا اختلاف تاریخ شروع و پایان بیشتر از ۷ روز نباشه 

پیشاپیش از زحمات شما متشکرم

**Comment by aliyr** [comment]
من هم همچین مشکلی رو دارم
اگر بشه که پیاده سازی بشه خیلی خوبه

**Comment by talkhabi** [comment]
سلام دوستان، ممنون از اینکه از این پلاگین استفاده میکنید
بنده مقداری تایمم پره و وقت نمیکنم روی این پروژه کار کنم
البته این فیچری که شما نیاز دارید در ساختار پروژه خیلی تغییرات ایجاد میکنه و کار زیادی میبره
ولی به محض اینکه فرصت بشه انجام میدم
متاسفانه هیچکدوم از دوستان در توسعه شرکت نمیکنند

**Comment by mhml1367** [comment]
من هم درخواست رفع این مشکل رو دارم

**Comment by akbarjoudi** [comment]
سلام و خسته نباشید.
من هم به این ویژگی نیاز و دارم

**Comment by mohammadfiroozi** [comment]
لطفا این ویژگی رو اضافه کنید

**Comment by alifakoor** [comment]
@talkhabi 
آقای تلخابی اول تشکر کنم بابت این پکیج عالی، هم عملکرد عالی داره هم ظاهر خیلی خوب
در رابطه با مشکل رنج، من هم خودم در خیلی از پروژه ها به این مشکل برخورد کردم و خوشحال میشم که اگر بتونم کمکی بکنم، اگر امکانش هست یک راه ارتباطی بدین تا بتونم چندتا سوال ازتون بپرسم
متشکرم

**Comment by hbsoftco** [comment]
+1

**Comment by AltiumWilliam** [comment]
با سلام
ضمن تشکر از این پکیج عالی، من نیز تقاضا این قابلیت را دارم

**Comment by AltiumWilliam** [comment]
من توضیحاتی در https://github.com/talkhabi/vue-persian-datetime-picker/issues/4#issuecomment-753013817 نوشتم و پیشنهاداتی هم دادم، اگر امکان داره ملاحظه فرمایید

**Comment by talkhabi** [comment]
@AltiumWilliam 
سلام، ممنون از شما
بله در جریان هستم، ممنون از پیشنهاداتتون
مدتی هست که دارم روی این فیچر کار میکنم ولی ساختار کل پروژه داره عوض میشه و نیازه که همه جوانب در نظر گرفته بشه
اشکالش هم از سمت بنده هست که از اول این موضوع رو در نظر نگرفتم و الآن باعث تغییرات خیلی زیادی شده،
اما خب در حال انجامه و در در مرحله بعد هم برای vue3

**Comment by AltiumWilliam** [comment]
> @AltiumWilliam
> سلام، ممنون از شما
> بله در جریان هستم، ممنون از پیشنهاداتتون
> مدتی هست که دارم روی این فیچر کار میکنم ولی ساختار کل پروژه داره عوض میشه و نیازه که همه جوانب در نظر گرفته بشه
> اشکالش هم از سمت بنده هست که از اول این موضوع رو در نظر نگرفتم و الآن باعث تغییرات خیلی زیادی شده،
> اما خب در حال انجامه و در در مرحله بعد هم برای vue3

سلام
از وقتی که برای این موضوع می گذارید کمال تشکر را دارم

**Comment by talkhabi** [comment]
سلام و درود
در ورژن 2.5.0 این مورد اضافه شد

**Comment by AltiumWilliam** [comment]
سلام و درود
تشکر فراوان. دقیقا همین مدنظرم بود! عالی عالی عالی! درود بر شما

**Comment by AltiumWilliam** [comment]
سلام مجدد
آقای تلخابی خجالت میکشم که این حرف را میزنم. یک ایده دارم که نمی دانم چقدر کاربرد خواهد داشت. این ایده الآن که قابلیت انتخاب بازه به پلاگین اضافه کردید راحت میشه به آن اضافه کرد. و جالب اینجاست که من در هیچ پلاگینی (خارجی یا ایرانی) تا حالا ندیدم!
قابلیت انتخاب آرایه ای از تاریخ ها! انتخاب چندگانه تاریخ! عملکردش هم به این صورت می تواند باشد که پس از باز شدن تقویم، هر تاریخی که کلیک شود به آرایه تاریخ های انتخابی اضافه شده و با کلیک مجدد روی همان تاریخ، از آرایه حذف شود.
همان طور که گفتم واقعا نمی دانم تا چه حد می تواند کاربردی باشد، برای مثال می توان در چنین برنامه ای از این قابلیت استفاده کرد. مثلا برنامه ای داریم که در آن هر تاریخی که انتخاب شود، در آن تاریخ برنامه یک ایمیل، یک پشتیبان یا یک کار خاصی را انجام دهد. در این حالت نیاز میشه که چندین تاریخ که بازه هم نیستند انتخاب شوند.
باز هم شرمنده که مزاحم شما شدم

**Comment by talkhabi** [comment]
سلام @AltiumWilliam 
multiple منظورتون هست
فکر کنم ویوتیفای داره
اون مورد رو هم اضافه میکنم ایشالا
الان دارم روی یه فیچر دیگه کار میکنم، به ترتیب انجام میشه چشم

**Comment by AltiumWilliam** [comment]
آقای تلخابی، خوشحال میشم اگر بتونم کمکی به شما کنم و گوشه ای از کار را بگیرم، کارتان آنقدر عالیست که برام افتخاره با شما کار کنم

**Comment by talkhabi** [comment]
@AltiumWilliam 
  ممنونم لطف داری عزیز
این موارد که انجام شد
