### ISSUE TITLE
مشکل پاک کردن تاریخ در تقویم قابل ویرایش

### ISSUE THREAD

**Issue by marjandejyab** [talkhabi/vue-persian-datetime-picker#8]
سلام و خسته نباشید
دوست عزیز من از تقویم شما در حالت قابل ویرایش
editable="true"
استفاده میکنم. مشکلی که وجود داره این هستش که زمانی که
input 
رو خالی میکنم
model
 متصل به اون خالی نمیشه. می تونید این موضوع رو دموی خودتون هم مشاهده بفرمایید.
آیا این امکان وجود داره که اگر کاربر یک تاریخ غیر معتبر تایپ کرد یا اینپوت رو خالی کرد
model 
را هم خالی کنید؟
یا اگه در حال حاضر روشی برای انجام این موضوع وجود دارد ممنون میشم که بنده رو راهنمایی بفرمایید.

**Comment by talkhabi** [comment]
سلام، این مشکل رفع شد
2bee9854f5f74cce8e208adaa56b5057f1d0e71e
