### ISSUE TITLE
اضافه کردن روز استثنا

### ISSUE THREAD

**Issue by soheil-ghs** [talkhabi/vue-persian-datetime-picker#80]
سلام و عرض ادب.می خواستم ببینم راهی هست اگر مثلا روز جمعه رو بعنوان روزهای غیر فعال انتخاب کرده باشیم یک جمعه خاص رو بعنوان استثنا فعال کنیم؟

**Comment by soheil-ghs** [comment]
سلام.ممنون از راهنماییتون مشکلم حل شد.واقعا این پکیج رو عالی و جامع نوشتین.خدا خیرتون بده

**Comment by talkhabi** [comment]
موفق باشید دوست عزیز
