### ISSUE TITLE
استفاده همزمان از Custom input و Different input and output values

### ISSUE THREAD

**Issue by javadjkm** [talkhabi/vue-persian-datetime-picker#81]
<p dir="rtl">سلام من میخوام تاریخ تو input شمسی دیده بشه ولی تو data میلادی ولی نمیتونم اینکارو تو Custom input انجام بدم بازم میلادی نشون میده

</p>
<pre><code>&lt;input
  type="text"
  class="form-control form-control-lg"
  v-model="date"
  id="my-custom-input"
  placeholder="select date"
/&gt;

&lt;date-picker
  v-model="date"
  format="jYYYY/jMM/jDD"
  element="my-custom-input"
/&gt;
</code></pre>

**Comment by talkhabi** [comment]
سلام، این دوتا آپشن باهم قابل استفاده نیستند فعلا
