### ISSUE TITLE
انتخاب سال ماه و روز به ترتیب

### ISSUE THREAD

**Issue by mehdi-haydari** [talkhabi/vue-persian-datetime-picker#84]
امکان انتخاب سال و ماه توی ایشو زیر اضافه شد
#70 

در صورت امکان سال ماه روز هم اضافه بشه. برای انتخاب تاریخ تولد و چیزهایی از این دست بسیار به درد بخور هست

**Comment by talkhabi** [comment]
سال ماه روز که الان هست !؟
چه مدلی منظور شماست؟

**Comment by mehdi-haydari** [comment]
مشکل رو با view="year" حل کردم
ممنون
