### ISSUE TITLE
مشکل در vue-persian-datetime-picker.js

### ISSUE THREAD

**Issue by marjandejyab** [talkhabi/vue-persian-datetime-picker#9]
سلام و خسته نباشید
ممنونم از اعمال تغییرات جدید.
دوست عزیز من ورژن 1.0.9 رو دانلود کردم اما در
build
شدن مشکل داره و فایل
moment-jalaali
رو نمیشناسه. ممنون میشم اگه این مورد برطرف بشه.
این پیغام خطای من هست.

ERROR in ./~/vue-persian-datetime-picker/~/moment-jalaali/index.js
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Source\****\****\node_modules\vue-persian-datetime-picker\node_modules\moment-jalaali\index.js'
 @ ./~/vue-persian-datetime-picker/dist/vue-persian-datetime-picker.js 1:82-107

**Comment by talkhabi** [comment]
npm install moment-jalaali
اینو نصب کردین؟

**Comment by marjandejyab** [comment]
سلام روزتون بخیر
بله این پکیج روی پروژه ما نصب هستش.
و با ورژن قبلی هم به خوبی کار میکنیم. اما بعد از آپدیت خطایی رو که براتون ارسال کردم رو میگیرم.
ممنون میشم راهنماییم کنین.

**Comment by madnik7** [comment]
در نگارش 1.0.9 moment-jalaali به صورت خودکار به همراه package نصب نمی شود. نصب جداگانه moment-jalaali  نیز فایده ندارد چون تقویم کماکان به دنبال moment  در پوشه خود می گردد و ما باید دستی moment را کپی کنیم. بهتر است moment با برنامه نصب شود یا آدرس دهی به صورت global باشد تا با نصب moment به صورت جدا این مشکل حل شود

**Comment by talkhabi** [comment]
@madnik7 
مومنت همیشه بیرون از پوشه تقویم نصب میشه
نیازی نیست که دستی کپی بشه

**Comment by talkhabi** [comment]
@marjandejyab 
من چندین جا این پکیج رو نصب کردم و مشکلی ندیدم
شما یه بار دیگه این ورژن رو حذف و نصب کن

**Comment by talkhabi** [comment]
سلام، موفق باشید
