### ISSUE TITLE
Open in menu

### ISSUE THREAD

**Issue by BashirRezaiee** [talkhabi/vue-persian-datetime-picker#93]
Hi, 
Thanks for this useful and awesome plugin.
I have used this plugin with vuetify. I have a problem when using this plugin inside [dialogs](https://vuetifyjs.com/en/components/dialogs), the picker does not appear. I think it's because of the dialog this plugin opens in it. I could not find any solution inside documentation. I have a suggestion if it could be possible that the picker opens in a menu. I have a demo from vuetify datepicker which opens both in dialogs and menus. 
[Vuetify Datepicker](https://vuetifyjs.com/en/components/date-pickers#date-pickers-in-dialog-and-menu)

**Comment by talkhabi** [comment]
Hi @BashirRezaiee thank you. 

Didn't using `append-to` solve this problem?
```html
<date-picker append-to="body" />
```
