### ISSUE TITLE
safari 01/01

### ISSUE THREAD

**Issue by EmadFani** [talkhabi/vue-persian-datetime-picker#94]
there is an issues on only safari browser that when you go to 01/01/xxxx there is two **1** of the date.
<img width="697" alt="Screen Shot 2020-02-12 at 1 28 02 PM" src="https://user-images.githubusercontent.com/25377578/74324041-aadb7480-4d9b-11ea-9b96-1919832858fa.png">
 PM.png…]()

**Comment by talkhabi** [comment]
This bug is also in Firefox 57 on older.
That seems to be a JavaScript computing bug from the browser side and I haven't found any solution to this.
What is your Safari version?

**Comment by EmadFani** [comment]
Version 13.0.5 (15608.5.11)

**Comment by talkhabi** [comment]
Hi @EmadFani,
Please check the changes
