### ISSUE TITLE
Support for the Gregorian calendar in other languages

### ISSUE THREAD

**Issue by peyman3d** [talkhabi/vue-persian-datetime-picker#95]
Hi, Thanks a lot for this great package.

Is there any way to have the Gregorian calendar in other languages like `ar`, `tr` or `fr`? 
I tried to change all the translations for `en` to make it looks like another language but it's a really dirty solution. I hope there is another way to do that like loading another locale on `momentjs`.

**Comment by talkhabi** [comment]
Hi @peyman3d thank you.

Unfortunately only `en` and `fa` are supported in component!
this is my bad and I'll fix it to support other languages.

So what can we do?
there is a quick (and dirty too!) way to update  `en` locale:
```js
import moment from 'moment'
import 'moment/locale/fr'
let localeData = moment.localeData('fr')
let newLocaleData = {}
for (let k in localeData) {
  if (localeData.hasOwnProperty(k))
    newLocaleData[k.replace('_', '')] = localeData[k]
}
moment.updateLocale('en', newLocaleData)
// import date picker
```

**Comment by peyman3d** [comment]
Dear @talkhabi 
Thanks for your quick response. I think this will be a good feature to have the Gregorian calendar in other languages. It'll make this great package even better.
I've used a solution close to yours. Hope to replace it with new updates :)
