### ISSUE TITLE
مشكل در نمايش سال جديد در موبايل

### ISSUE THREAD

**Issue by amyounesi** [talkhabi/vue-persian-datetime-picker#96]
متاسفانه در موبايل سال جديد دچارمشكل است ٨ روز اول ولي در كامپيوتر مشكل ندارد[عكس مشكل](http://s6.picofile.com/file/8391322600/C695D8BA_74AF_49E4_A80C_A236D8672FC9.png)

**Comment by talkhabi** [comment]
duplicate #94
