### ISSUE TITLE
Triggering (open datepicker Modal Method)

### ISSUE THREAD

**Issue by beigiz** [talkhabi/vue-persian-datetime-picker#98]
salam
ghabeliat programmatically triggering (open and close modal with js) alan hast 
man chizi natunestam peyda konam dar in rabete

mersi az kare zibatun

**Comment by talkhabi** [comment]
```html
<date-picker @open="onOpen" />
```

**Comment by beigiz** [comment]
salam,
Open Event Trigger Manzooram nabood
inke betunam az jaye dige masalan click kardan roo ye button 
modale date picker ro baz konam

ex
`<button @click="openDatePickerModal"></button>`
<date-picker v-model="date> 
</date-picker>
`methods: {
  openDatePickerModal(){
 // some code to open date-picker modal
}
}
`

**Comment by talkhabi** [comment]
```html
<date-picker :show="showDatePicker" @close="showDatePicker= false" />
<script>
export default {
  data() {
     return {
        showDatePicker: false
     }
  }
}
</script>
```
